// Generated by tools/menugen/menugen.py from the Xbox mnu3.HIP, then kept by
// hand. This file is the source of MNU3's groups, conditionals, timers,
// dispatchers, sound effects and portals now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static xGroupAsset GroupDefaultsInit()
{
    xGroupAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeGroup;
    a.baseFlags = 0xD;
    return a;
}

static const xGroupAsset kGroupDefaults = GroupDefaultsInit();

void MNU3_BuildGroup(iAssetPkg& p)
{
    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("D PAUSE GROUP"), a);
        p.Item(H("MNU3 PAUSE RETURN GAME UIF"));
        p.Item(H("MNU3 PAUSE OPTIONS UIF"));
        p.Item(H("MNU3 PAUSE TAKE BUS UIF"));
        p.Item(0x534EEBC0);
        p.Item(H("MNU3 PAUSE MGR UIF"));
        p.Item(H("MNU3 ARROW UP UI"));
        p.Item(H("MNU3 ARROW DOWN UI"));
        p.Item(H("MNU3 LEVEL OFF UI1"));
        p.Item(H("MNU3 LEVEL OFF UI2"));
        p.Item(H("MNU3 LEVEL OFF UI3"));
        p.Item(H("MNU3 LEVEL OFF UI4"));
        p.Item(H("MNU3 LEVEL OFF UI5"));
        p.Item(H("MNU3 LEVEL OFF UI6"));
        p.Item(H("MNU3 LEVEL OFF UI7"));
        p.Item(H("MNU3 LEVEL OFF UI8"));
        p.Item(H("MNU3 LEVEL OFF UI9"));
        p.Item(H("MNU3 LEVEL OFF UI10"));
        p.Item(H("MNU3 LEVEL OFF UI11"));
        p.Item(H("MNU3 LEVEL OFF UI12"));
        p.Item(H("MNU3 LEVEL OFF UI13"));
        p.Item(H("MNU3 LEVEL OFF UI14"));
        p.Item(H("MNU3 TASK UI 08"));
        p.Item(H("MNU3 TASK UI 07"));
        p.Item(H("MNU3 TASK UI 06"));
        p.Item(H("MNU3 TASK UI 05"));
        p.Item(H("MNU3 TASK UI 04"));
        p.Item(H("MNU3 TASK UI 03"));
        p.Item(H("MNU3 TASK UI 02"));
        p.Item(H("MNU3 TASK UI 01"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 START BKG GROUP"), a);
        p.Item(H("MNU3 BLUE ALPHA 2 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("D MNU4 PAUSE OPTIONS GROUP "), a);
        p.Item(H("MNU3 PAUSE OPTION MGR UIF"));
        p.Item(H("MNU3 PAUSE OPTION QUIT UIF"));
        p.Item(H("MNU3 PAUSE OPTION LOAD UIF"));
        p.Item(H("MNU3 PAUSE OPTION CONTROLS UIF"));
        p.Item(H("MNU3 PAUSE OPTION SAVE UIF"));
        p.Item(H("MNU3 PAUSE OPTION PRESS X UIF"));
        p.Item(H("MNU3 PAUSE OPTION PRESS TRI UIF"));
        p.Item(0x39F0DA6C);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 LEVEL BUBBLE GROUP"), a);
        p.Item(H("MNU3 LEVEL ON UI14"));
        p.Item(H("MNU3 LEVEL ON UI13"));
        p.Item(H("MNU3 LEVEL ON UI12"));
        p.Item(H("MNU3 LEVEL ON UI11"));
        p.Item(H("MNU3 LEVEL ON UI10"));
        p.Item(H("MNU3 LEVEL ON UI9"));
        p.Item(H("MNU3 LEVEL ON UI8"));
        p.Item(H("MNU3 LEVEL ON UI7"));
        p.Item(H("MNU3 LEVEL ON UI6"));
        p.Item(H("MNU3 LEVEL ON UI5"));
        p.Item(H("MNU3 LEVEL ON UI4"));
        p.Item(H("MNU3 LEVEL ON UI3"));
        p.Item(H("MNU3 LEVEL ON UI2"));
        p.Item(H("MNU3 LEVEL ON UI1"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 TASK GLOW UI GROUP"), a);
        p.Item(H("MNU3 TASK GLOW UI 08"));
        p.Item(H("MNU3 TASK GLOW UI 07"));
        p.Item(H("MNU3 TASK GLOW UI 06"));
        p.Item(H("MNU3 TASK GLOW UI 05"));
        p.Item(H("MNU3 TASK GLOW UI 04"));
        p.Item(H("MNU3 TASK GLOW UI 03"));
        p.Item(H("MNU3 TASK GLOW UI 02"));
        p.Item(H("MNU3 TASK GLOW UI 01"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 TASK UIF GROUP"), a);
        p.Item(H("MNU3 PAUSE TASK UIF 08"));
        p.Item(H("MNU3 PAUSE TASK UIF 07"));
        p.Item(H("MNU3 PAUSE TASK UIF 06"));
        p.Item(H("MNU3 PAUSE TASK UIF 05"));
        p.Item(H("MNU3 PAUSE TASK UIF 04"));
        p.Item(H("MNU3 PAUSE TASK UIF 03"));
        p.Item(H("MNU3 PAUSE TASK UIF 02"));
        p.Item(H("MNU3 PAUSE TASK UIF 01"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 PAUSE OPTIONS BKG GROUP"), a);
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 PAUSE CONTROL NTSC GROUP"), a);
        p.Item(H("MNU3 PAUSE CONTROL MGR NTSC UIF"));
        p.Item(0xCF736C17);
        p.Item(0x94D995A6);
        p.Item(H("MNU3 BLUE ALPHA 3 UI"));
        p.Item(H("MNU3 CONTROL SFX UIF"));
        p.Item(H("MNU3 CONTROL MUSIC UIF"));
        p.Item(H("MNU3 CONTROL VIBE UIF"));
        p.Item(H("MNU3 CONTROL SOUND UIF"));
        p.Item(0xB43E3131);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 MUSIC COND GROUP"), a);
        p.Item(H("MNU3 MUSIC VOL COND 0"));
        p.Item(H("MNU3 MUSIC VOL COND 1"));
        p.Item(H("MNU3 MUSIC VOL COND 2"));
        p.Item(H("MNU3 MUSIC VOL COND 3"));
        p.Item(H("MNU3 MUSIC VOL COND 4"));
        p.Item(H("MNU3 MUSIC VOL COND 5"));
        p.Item(H("MNU3 MUSIC VOL COND 6"));
        p.Item(H("MNU3 MUSIC VOL COND 7"));
        p.Item(H("MNU3 MUSIC VOL COND 8"));
        p.Item(H("MNU3 MUSIC VOL COND 9"));
        p.Item(H("MNU3 MUSIC VOL COND 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 SFX COND GROUP"), a);
        p.Item(H("MNU3 SFX VOL COND 0"));
        p.Item(H("MNU3 SFX VOL COND 1"));
        p.Item(H("MNU3 SFX VOL COND 2"));
        p.Item(H("MNU3 SFX VOL COND 3"));
        p.Item(H("MNU3 SFX VOL COND 4"));
        p.Item(H("MNU3 SFX VOL COND 5"));
        p.Item(H("MNU3 SFX VOL COND 6"));
        p.Item(H("MNU3 SFX VOL COND 7"));
        p.Item(H("MNU3 SFX VOL COND 8"));
        p.Item(H("MNU3 SFX VOL COND 9"));
        p.Item(H("MNU3 SFX VOL COND 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 MIN MAX GROUP"), a);
        p.Item(H("MNU3 CONTROL MIN UIF"));
        p.Item(H("MNU3 CONTROL MAX UIF"));
        p.Item(H("MNU3 HOUSE SQUIDWARD UI"));
        p.Item(H("MNU3 HOUSE SPONGEBOB UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 ON OFF GROUP"), a);
        p.Item(H("MNU3 CONTROL ON UIF"));
        p.Item(H("MNU3 CONTROL OFF UIF"));
        p.Item(H("MNU3 CONTROL OFF UI"));
        p.Item(H("MNU3 CONTROL ON UI"));
        p.Item(H("MNU3 HOUSE SQUIDWARD UI"));
        p.Item(H("MNU3 HOUSE SPONGEBOB UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 CONTROL HASH ALL GROUP"), a);
        p.Item(H("MNU3 CONTROL HASH B UI 0"));
        p.Item(H("MNU3 CONTROL HASH B UI 1"));
        p.Item(H("MNU3 CONTROL HASH B UI 2"));
        p.Item(H("MNU3 CONTROL HASH B UI 3"));
        p.Item(H("MNU3 CONTROL HASH B UI 4"));
        p.Item(H("MNU3 CONTROL HASH B UI 5"));
        p.Item(H("MNU3 CONTROL HASH B UI 6"));
        p.Item(H("MNU3 CONTROL HASH B UI 7"));
        p.Item(H("MNU3 CONTROL HASH B UI 8"));
        p.Item(H("MNU3 CONTROL HASH B UI 9"));
        p.Item(H("MNU3 CONTROL HASH B UI 10"));
        p.Item(H("MNU3 CONTROL HASH BASE GROUP"));
        p.Item(H("MNU3 KABLAM ON UI"));
        p.Item(H("MNU3 KABLAM OFF UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 CONTROL HASH BASE GROUP"), a);
        p.Item(H("MNU3 CONTROL HASH UI 0"));
        p.Item(H("MNU3 CONTROL HASH UI 1"));
        p.Item(H("MNU3 CONTROL HASH UI 2"));
        p.Item(H("MNU3 CONTROL HASH UI 3"));
        p.Item(H("MNU3 CONTROL HASH UI 4"));
        p.Item(H("MNU3 CONTROL HASH UI 5"));
        p.Item(H("MNU3 CONTROL HASH UI 6"));
        p.Item(H("MNU3 CONTROL HASH UI 7"));
        p.Item(H("MNU3 CONTROL HASH UI 8"));
        p.Item(H("MNU3 CONTROL HASH UI 9"));
        p.Item(H("MNU3 CONTROL HASH UI 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 SOUND MODE COND GROUP"), a);
        p.Item(H("MNU3 SOUND MODE COND "));
        p.Item(H("MNU3 SOUND MODE TOGGLE COND "));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 VIBE MODE COND GROUP"), a);
        p.Item(H("MNU3 VIBE MODE COND "));
        p.Item(H("MNU3 VIBE MODE TOGGLE COND "));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 KABLAM ALL GROUP"), a);
        p.Item(H("MNU3 KABLAM OFF UI"));
        p.Item(H("MNU3 KABLAM ON UI"));
        p.Item(H("MNU3 CONTROL SB ON UI"));
        p.Item(H("MNU3 CONTROL SB OFF UI"));
        p.Item(H("MNU3 ON OFF GROUP"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 KABLAM ON GROUP"), a);
        p.Item(H("MNU3 KABLAM ON UI"));
        p.Item(H("MNU3 CONTROL SB ON UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 KABLAM OFF GROUP"), a);
        p.Item(H("MNU3 KABLAM OFF UI"));
        p.Item(H("MNU3 CONTROL SB OFF UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LD GAMESLOT GROUP"), a);
        for (S32 i = 0; i < ISAVESCREEN_ROWS; i++)
        {
            char name[32];
            sprintf(name, ISAVESCREEN_LOAD_ROW, (int)i);
            p.Item(H(name));
        }
        p.Item(H("LD LOAD GAME UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 SCREEN ADJUST GROUP"), a);
        p.Item(H("MNU3 SCREEN MGR UIF"));
        p.Item(H("MNU3 SCREEN INF UIF"));
        p.Item(H("MNU3 SCREEN CANCEL UIF"));
        p.Item(H("MNU3 SCREEN RESET UIF"));
        p.Item(H("MNU3 SCREEN ACCEPT UIF"));
        p.Item(H("MNU3 BLUE ALPHA 2 UI"));
        p.Item(0xC57D73F6);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 START GROUP"), a);
        p.Item(H("MNU3 START PRESS X UIF"));
        p.Item(H("MNU3 START PROMO UIF"));
        p.Item(H("MNU3 START CREDITS UIF"));
        p.Item(H("MNU3 START CONTROLS UIF"));
        p.Item(H(ISETTINGS_TITLE_ENTRY));
        p.Item(H("MNU3 START LOAD UIF"));
        p.Item(H("MNU3 START NEWGAME UIF"));
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.Item(H("MNU3 START MAIN MENU UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 PRESS START GROUP"), a);
        p.Item(H("MNU3 PRESS START UIF"));
        p.Item(H("START TIMER 01"));
        p.Item(H("START TIMER 02"));
        p.Item(H("MNU3 PRESS START 02 UIF"));
        p.Item(H("MNU3 TITLE CARD UI"));
        p.Link(eEventUIFocusOn, eEventUISelect, H("MNU3 PRESS START UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 LD TITLE GROUP"), a);
        p.Item(H("MNU3 LD PRESS TRIANGLE"));
        p.Item(H("MNU3 LD PRESS X"));
        p.Item(H("LD LOAD GAME UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU3 MONO STEREO GROUP"), a);
        p.Item(H("MNU3 CONTROL OFF UI"));
        p.Item(H("MNU3 CONTROL ON UI"));
        p.Item(H("MNU3 HOUSE SQUIDWARD UI"));
        p.Item(H("MNU3 HOUSE SPONGEBOB UI"));
        p.Item(H("MNU3 CONTROL MONO UIF"));
        p.Item(H("MNU3 CONTROL STEREO UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("LD MAKE INVISIBLE"), a);
        p.Item(H("MNU3 THUMBICON"));
        p.Item(H("MNU3 DISK FREE"));
        p.Item(H("LD LOAD GAME UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 START NEW GAME BKG GROUP"), a);
        p.Item(H("BLUE ALPHA 1 BAMBOO UI"));
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("CAUSTICS TEXTURE GROUP"), a);
        p.Item(H("caustics_01_001"));
        p.Item(H("caustics_01_002"));
        p.Item(H("caustics_01_003"));
        p.Item(H("caustics_01_004"));
        p.Item(H("caustics_01_005"));
        p.Item(H("caustics_01_006"));
        p.Item(H("caustics_01_007"));
        p.Item(H("caustics_01_008"));
        p.Item(H("caustics_01_009"));
        p.Item(H("caustics_01_010"));
        p.Item(H("caustics_01_011"));
        p.Item(H("caustics_01_012"));
        p.Item(H("caustics_01_013"));
        p.Item(H("caustics_01_014"));
        p.Item(H("caustics_01_015"));
        p.Item(H("caustics_01_016"));
        p.Item(H("caustics_01_017"));
        p.Item(H("caustics_01_018"));
        p.Item(H("caustics_01_019"));
        p.Item(H("caustics_01_020"));
        p.Item(H("caustics_01_021"));
        p.Item(H("caustics_01_022"));
        p.Item(H("caustics_01_023"));
        p.Item(H("caustics_01_024"));
        p.Item(H("caustics_01_025"));
        p.Item(H("caustics_01_026"));
        p.Item(H("caustics_01_027"));
        p.Item(H("caustics_01_028"));
        p.Item(H("caustics_01_029"));
        p.Item(H("caustics_01_030"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE PROMO GROUP"), a);
        p.Item(H("MNU3 PAUSE PROMO MGR UIF"));
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.Item(H("MNU3 LD PRESS X"));
        p.Item(H("MNU3 LD PRESS TRIANGLE"));
        p.Item(H("MNU3 PROMO TITLE 00"));
        p.Item(H("MNU3 PROMO TITLE 01"));
        p.Item(H("MNU3 PROMO TITLE 03"));
        p.Item(H("MNU3 PROMO TITLE 02"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE CONTROLS PAL GROUP"), a);
        p.Item(0xCF736C17);
        p.Item(0x94D995A6);
        p.Item(H("MNU3 BLUE ALPHA 3 UI"));
        p.Item(H("MNU3 CONTROL SCREEN PAL UIF"));
        p.Item(H("MNU3 PAUSE CONTROL MGR PAL UIF"));
        p.Item(H("MNU3 CONTROL MUSIC PAL UIF"));
        p.Item(H("MNU3 CONTROL SFX PAL UIF"));
        p.Item(H("MNU3 CONTROL SOUND PAL UIF"));
        p.Item(H("MNU3 CONTROL VIBE PAL UIF"));
        p.Item(0xB43E3131);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("INTRO TEXTURE GROUP"), a);
        p.Item(H("ui_intro001"));
        p.Item(H("ui_intro002"));
        p.Item(H("ui_intro003"));
        p.Item(H("ui_intro004"));
        p.Item(H("ui_intro005"));
        p.Item(H("ui_intro006"));
        p.Item(H("ui_intro007"));
        p.Item(H("ui_intro008"));
        p.Item(H("ui_intro009"));
        p.Item(H("ui_intro010"));
        p.Item(H("ui_intro011"));
        p.Item(H("ui_intro012"));
        p.Item(H("ui_intro013"));
        p.Item(H("ui_intro014"));
        p.Item(H("ui_intro015"));
        p.Item(H("ui_intro016"));
        p.Item(H("ui_intro017"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("BUBBLE WIPE MARKER GROUP"), a);
        p.Item(H("BUBBLE WIPE MARKER 01"));
        p.Item(H("BUBBLE WIPE MARKER 02"));
        p.Item(H("BUBBLE WIPE MARKER 03"));
        p.Item(H("BUBBLE WIPE MARKER 04"));
        p.Item(H("BUBBLE WIPE MARKER 05"));
        p.Item(H("BUBBLE WIPE MARKER 06"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("BUBBLE WIPE MARKER GROUP 02"), a);
        p.Item(H("BUBBLE WIPE MARKER 07"));
        p.Item(H("BUBBLE WIPE MARKER 08"));
        p.Item(H("BUBBLE WIPE MARKER 09"));
        p.Item(H("BUBBLE WIPE MARKER 10"));
        p.Item(H("BUBBLE WIPE MARKER 11"));
        p.Item(H("BUBBLE WIPE MARKER 12"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("BUBBLE WIPE MARKER GROUP 03"), a);
        p.Item(H("BUBBLE WIPE MARKER 13"));
        p.Item(H("BUBBLE WIPE MARKER 14"));
        p.Item(H("BUBBLE WIPE MARKER 15"));
        p.Item(H("BUBBLE WIPE MARKER 16"));
        p.Item(H("BUBBLE WIPE MARKER 17"));
        p.Item(H("BUBBLE WIPE MARKER 18"));
        p.Item(H("BUBBLE WIPE MARKER 19"));
        p.Item(H("BUBBLE WIPE MARKER 20"));
        p.Item(H("BUBBLE WIPE MARKER 21"));
        p.Item(H("BUBBLE WIPE MARKER 22"));
        p.Item(H("BUBBLE WIPE MARKER 23"));
        p.Item(H("BUBBLE WIPE MARKER 24"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE CONTROLS GC_XB GROUP"), a);
        p.Item(0xCF736C17);
        p.Item(0x94D995A6);
        p.Item(H("MNU3 BLUE ALPHA 3 UI"));
        p.Item(H("MNU3 CONTROL MUSIC GC_XB UIF"));
        p.Item(H("MNU3 CONTROL SFX GC_XB UIF"));
        p.Item(H("MNU3 CONTROL VIBE GC_XB UIF"));
        p.Item(0x5983E50D);
        p.Item(0xB43E3131);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', 0x5D99DABC, a);
        p.Item(0xCF736C17);
        p.Item(0x94D995A6);
        p.Item(H("MNU3 BLUE ALPHA 3 UI"));
        p.Item(0x4991A567);
        p.Item(H("MNU3 CONTROL SFX GC_XB PAL UIF"));
        p.Item(H("MNU3 CONTROL VIBE GC_XB PAL UIF"));
        p.Item(0x26CEB12C);
        p.Item(0xB43E3131);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE PROMO XB GROUP"), a);
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.Item(H("MNU3 LD PRESS X"));
        p.Item(H("MNU3 LD PRESS TRIANGLE"));
        p.Item(H("MNU3 PROMO TITLE XB 00"));
        p.Item(H("MNU3 PAUSE PROMO MGR XB UIF"));
        p.Item(H("MNU3 PROMO TITLE XB 03"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("BUBBLE EMITERS ALL MNU3"), a);
        p.Item(H("BUBBLE EMIT"));
        p.Item(H("BUBBLE SMALL EMIT"));
        p.Item(H("BUBBLE SMALL EMIT 02"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE PROMO PS2_PAL GROUP"), a);
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.Item(H("MNU3 LD PRESS X"));
        p.Item(H("MNU3 LD PRESS TRIANGLE"));
        p.Item(H("MNU3 PROMO TITLE PS2_PAL 03"));
        p.Item(H("MNU3 PROMO TITLE PS2_PAL 02"));
        p.Item(H("MNU3 PROMO TITLE PS2_PAL 01"));
        p.Item(0x0AF127D1);
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("MNU3 PAUSE PROMO XB PAL GROUP"), a);
        p.Item(H("MNU3 BLUE ALPHA 1 UI"));
        p.Item(H("MNU3 LD PRESS X"));
        p.Item(H("MNU3 LD PRESS TRIANGLE"));
        p.Item(H("MNU3 PAUSE PROMO MGR XB PAL UIF"));
        p.Item(H("MNU3 PROMO TITLE XB PAL 03"));
        p.End();
    }
}

static zCondAsset CondDefaultsInit()
{
    zCondAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeCond;
    a.baseFlags = 0xD;
    a.constNum = 1;
    a.expr1 = H("Music Volume");
    return a;
}

static const zCondAsset kCondDefaults = CondDefaultsInit();

void MNU3_BuildCond(iAssetPkg& p)
{
    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Sound mode");
        p.Begin('COND', H("MNU3 SOUND MODE COND "), a);
        p.Link(eEventFalse, eEventVisible, H("MNU3 KABLAM OFF GROUP"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventVisible, H("MNU3 KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventInvisible, H("MNU3 KABLAM OFF GROUP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Sound mode");
        p.Begin('COND', H("MNU3 SOUND MODE TOGGLE COND "), a);
        p.Link(eEventTrue, eEventDispatcher_SoundMono, H("MNU3 CONTROLS DISP"));
        p.Link(eEventFalse, eEventDispatcher_SoundStereo, H("MNU3 CONTROLS DISP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Vibration is on");
        p.Begin('COND', H("MNU3 VIBE MODE COND "), a);
        p.Link(eEventFalse, eEventVisible, H("MNU3 KABLAM OFF GROUP"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventVisible, H("MNU3 KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventInvisible, H("MNU3 KABLAM OFF GROUP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Vibration is on");
        p.Begin('COND', H("MNU3 VIBE MODE TOGGLE COND "), a);
        p.Link(eEventTrue, eEventDispatcher_PadVibrateOff, H("MNU3 CONTROLS DISP"));
        p.Link(eEventFalse, eEventDispatcher_PadVibrateOn, H("MNU3 CONTROLS DISP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 0;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 0"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 0"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 0"));
        p.Link(eEventTrue, eEventPlay, H("MNU3 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 1"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 1"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 1"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 2;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 2"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 2"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 2"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 3;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 3"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 3"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 3"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 4;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 4"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 4"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 4"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 5;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 5"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 5"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 5"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 6;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 6"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 6"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 6"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 7;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 7"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 7"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 7"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 8;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 8"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 8"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 8"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 9;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 9"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 9"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 9"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 10;
        p.Begin('COND', H("MNU3 MUSIC VOL COND 10"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 10"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 10"));
        p.Link(eEventTrue, eEventPlay, H("MNU3 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 0;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 0"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 0"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 0"));
        p.Link(eEventTrue, eEventPlay, H("MNU3 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 1"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 1"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 1"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 2;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 2"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 2"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 2"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 3;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 3"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 3"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 3"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 4;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 4"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 4"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 4"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 5;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 5"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 5"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 5"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 6;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 6"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 6"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 6"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 7;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 7"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 7"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 7"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 8;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 8"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 8"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 8"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 9;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 9"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 9"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 9"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 10;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("MNU3 SFX VOL COND 10"), a);
        p.Link(eEventTrue, eEventVisible, H("MNU3 CONTROL HASH B UI 10"));
        p.Link(eEventFalse, eEventInvisible, H("MNU3 CONTROL HASH B UI 10"));
        p.Link(eEventTrue, eEventPlay, H("MNU3 PING SFX"));
        p.End();
    }
}

static xTimerAsset TimerDefaultsInit()
{
    xTimerAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeTimer;
    a.baseFlags = 0x1D;
    a.seconds = 0.1f;
    return a;
}

static const xTimerAsset kTimerDefaults = TimerDefaultsInit();

void MNU3_BuildTimer(iAssetPkg& p)
{
    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER4"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER4"));
        p.Link(eEventRun, eEventVisible, H("MNU3 ARROW UP GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("MNU3 ARROW UP GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER5"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER5"));
        p.Link(eEventRun, eEventVisible, H("MNU3 ARROW DOWN GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("MNU3 ARROW DOWN GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER6"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER6"));
        p.Link(eEventRun, eEventVisible, H("MNU3 CONTROL OFF GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("MNU3 CONTROL OFF GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER7"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER7"));
        p.Link(eEventRun, eEventVisible, H("MNU3 CONTROL ON GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("MNU3 CONTROL ON GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER9"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER9"));
        p.Link(eEventExpired, eEventVisible, H("MNU3 BLUE ALPHA 1 UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.5f;
        p.Begin('TIMR', H("START TIMER 01"), a);
        p.Link(eEventExpired, eEventReset, H("START TIMER 01"));
        p.Link(eEventExpired, eEventRun, H("START TIMER 02"));
        p.Link(eEventRun, eEventVisible, H("MNU3 PRESS START UIF"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.2f;
        p.Begin('TIMR', H("START TIMER 02"), a);
        p.Link(eEventExpired, eEventReset, H("START TIMER 02"));
        p.Link(eEventExpired, eEventRun, H("START TIMER 01"));
        p.Link(eEventRun, eEventInvisible, H("MNU3 PRESS START UIF"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 3.0f;
        p.Begin('TIMR', H("HOUSE CAM TIMER"), a);
        p.Link(eEventSceneBegin, eEventRun, H("HOUSE CAM TIMER"));
        p.Link(eEventExpired, eEventSwitch, H("HOUSECAM2"));
        p.Link(eEventExpired, eEventReset, H("HOUSE CAM TIMER"));
        p.Link(eEventExpired, eEventRun, H("HOUSE CAM TIMER 02"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 2.0f;
        p.Begin('TIMR', H("HOUSE CAM TIMER 04"), a);
        p.Link(eEventExpired, eEventReset, H("HOUSE CAM TIMER 04"));
        p.Link(eEventExpired, eEventUIFocusOn, H("MNU3 PRESS START GROUP"));
        p.Link(eEventExpired, eEventRun, H("START TIMER 01"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 1.5f;
        p.Begin('TIMR', H("HOUSE CAM TIMER 02"), a);
        p.Link(eEventExpired, eEventReset, H("HOUSE CAM TIMER 02"));
        p.Link(eEventExpired, eEventRun, H("HOUSE CAM TIMER 03"));
        p.Link(eEventExpired, eEventOff, H("BUBBLE SYS"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 3.5f;
        p.Begin('TIMR', H("HOUSE CAM TIMER 03"), a);
        p.Link(eEventExpired, eEventReset, H("HOUSE CAM TIMER 03"));
        p.Link(eEventExpired, eEventRun, H("HOUSE CAM TIMER 04"));
        p.Link(eEventRun, eEventVisible, H("MNU3 TITLE CARD HI UI"));
        p.Link(eEventExpired, eEventInvisible, H("MNU3 TITLE CARD HI UI"));
        p.Link(eEventExpired, eEventOff, H("BUBBLE SMALL EMIT"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.6f;
        p.Begin('TIMR', H("NEWGAME \"NO\" DELAY TIMER"), a);
        p.Link(eEventExpired, eEventReset, H("NEWGAME \"NO\" DELAY TIMER"));
        p.Link(eEventExpired, eEventDispatcher_SetGameState_FirstTime, H("MNU3 PAUSE STATE DISP"));
        p.End();
    }
}

static xBaseAsset DispatcherDefaultsInit()
{
    xBaseAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeDispatcher;
    a.baseFlags = 0xD;
    return a;
}

static const xBaseAsset kDispatcherDefaults = DispatcherDefaultsInit();

void MNU3_BuildDispatcher(iAssetPkg& p)
{
    {
        xBaseAsset a = kDispatcherDefaults;
        a.baseFlags = 0xF;
        p.Begin('DPAT', H("MNU3 PAUSE STATE DISP"), a);
        p.Link(eEventDispatcher_PauseState_Pause, eEventUIFocusOn, H("D PAUSE GROUP"));
        p.Link(eEventDispatcher_PauseState_Pause, eEventUISelect, H("MNU3 PAUSE MGR UIF"));
        p.Link(eEventDispatcher_GameState_Play, eEventUIFocusOff_Unselect, H("D PAUSE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("D PAUSE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("MNU3 START BKG GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventUIFocusOff_Unselect, H("MNU3 LEVEL BUBBLE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("MNU3 LEVEL BUBBLE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("MNU3 PAUSE OPTIONS BKG GROUP"));
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        p.Begin('DPAT', H("MNU3 CONTROLS DISP"), a);
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        p.Begin('DPAT', H("MNU3 PRESS START DISP"), a);
        p.Link(eEventSceneBegin, eEventStartConversation, H("HOUSECAM"));
        p.Link(eEventSceneBegin, eEventSwitch, H("HOUSECAM"));
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        a.baseFlags = 0x1D;
        p.Begin('DPAT', H("END OF CREDITS DISP"), a);
        p.Link(eEventCreditsEnded, eEventPlay, H("MNU3 BACK SFX"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventEndConversation, H("HOUSECAM"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventSwitch, H("HOUSECAM2"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventUIFocusOn, H("MNU3 START GROUP"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventUISelect, H("MNU3 START CREDITS UIF"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventInvisible, H("MNU3 LD PRESS TRIANGLE"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventUIFocusOff_Unselect, H("_MNU3 CREDITS MGR UIF"), 0.0f, 0.0f, 0.0f, 0.0f, H("menu_credits_p2_gc_xb"));
        p.Link(eEventCreditsEnded, eEventVisible, H("AAA CAUSTICS SURFACE UI"), iAssetParamID(H("menu_credits_p2_gc_xb")));
        p.End();
    }
}

static xSFXAsset SFXDefaultsInit()
{
    xSFXAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeSFX;
    a.baseFlags = 0xD;
    a.flagsSFX = 0x1C0;
    a.freqm = 1.0f;
    a.soundAssetID = H("mnu3_Bub_amb_loop");
    a.priority = 128;
    a.volume = 91;
    a.pos = xVec3{ 64.2824f, 29.8777f, 64.2824f };
    a.innerRadius = 10.0f;
    return a;
}

static const xSFXAsset kSFXDefaults = SFXDefaultsInit();

void MNU3_BuildSFX(iAssetPkg& p)
{
    {
        xSFXAsset a = kSFXDefaults;
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU3 AMBIENT SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_SB_jog1L");
        p.Begin('SFX ', H("MNU3 MOVE A SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_SB_jog1R");
        p.Begin('SFX ', H("MNU3 MOVE B SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_Bubble_wand");
        p.Begin('SFX ', H("MNU3 CONFIRM SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_Pop_in");
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU3 PING SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_Kelp_bubbles");
        p.Begin('SFX ', H("MNU3 BACK SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_castle_fill");
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU3 EXIT SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu3_sax");
        p.Begin('SFX ', H("MNU3 DENY SFX"), a);
        p.End();
    }
}

static xPortalAsset PortalDefaultsInit()
{
    xPortalAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypePortal;
    a.baseFlags = 0x1D;
    a.assetCameraID = H("STARTCAM");
    a.assetMarkerID = 0x76E17D6D;
    a.ang = 225.0f;
    a.sceneID = iAssetTag("PG12");
    return a;
}

static const xPortalAsset kPortalDefaults = PortalDefaultsInit();

void MNU3_BuildPortal(iAssetPkg& p)
{
    {
        xPortalAsset a = kPortalDefaults;
        p.Begin('PORT', H("TOPG12"), a);
        p.End();
    }
}
