// Generated by tools/menugen/menugen.py from the Xbox mnu3.HIP, then kept by
// hand. This file is the source of MNU3's asset list now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

// The types this package builds. The HIP's own assets of these types are
// never seen; everything else in it is used as shipped.
extern const U32 kMNU3OwnedTypes[] = { 'TEXT', 'UI  ', 'UIFT', 'GRUP', 'COND', 'TIMR', 'DPAT', 'SFX ', 'PORT', 0 };

void MNU3_BuildText(iAssetPkg& p);
void MNU3_BuildUI(iAssetPkg& p);
void MNU3_BuildUIFont(iAssetPkg& p);
void MNU3_BuildGroup(iAssetPkg& p);
void MNU3_BuildCond(iAssetPkg& p);
void MNU3_BuildTimer(iAssetPkg& p);
void MNU3_BuildDispatcher(iAssetPkg& p);
void MNU3_BuildSFX(iAssetPkg& p);
void MNU3_BuildPortal(iAssetPkg& p);

void MNU3_Build(iAssetPkg& p)
{
    MNU3_BuildText(p);
    MNU3_BuildUI(p);
    MNU3_BuildUIFont(p);
    MNU3_BuildGroup(p);
    MNU3_BuildCond(p);
    MNU3_BuildTimer(p);
    MNU3_BuildDispatcher(p);
    MNU3_BuildSFX(p);
    MNU3_BuildPortal(p);
}
