// Generated by tools/menugen/menugen.py from the Xbox mnu3.HIP, then kept by
// hand. This file is the source of MNU3's UI widgets now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static zUIAsset UIDefaultsInit()
{
    zUIAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeUI;
    a.baseFlags = 0xD;
    a.moreFlags = 0x2;
    a.pos = xVec3{ 0.0f, 0.0f, 90.0f };
    a.scale = xVec3{ 1.0f, 1.0f, 1.0f };
    a.redMult = 1.0f;
    a.greenMult = 1.0f;
    a.blueMult = 1.0f;
    a.seeThru = 1.0f;
    a.seeThruSpeed = 255.0f;
    a.uiFlags = 0x34;
    a.dim[0] = 30; a.dim[1] = 30;
    a.textureID = H("ui_bubble_small");
    a.uvb[0] = 1.0f; a.uvb[1] = 0.0f;
    a.uvc[0] = 1.0f; a.uvc[1] = 1.0f;
    a.uvd[0] = 0.0f; a.uvd[1] = 1.0f;
    return a;
}

static const zUIAsset kUIDefaults = UIDefaultsInit();

void MNU3_BuildUI(iAssetPkg& p)
{
    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 120.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_pineapple_off");
        p.Begin('UI  ', H("MNU3 ARROW UP UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 120.0f, 0.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_pineapple_on");
        p.Begin('UI  ', H("MNU3 ARROW UP GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 310.0f, 0.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_pineapple_on");
        a.uva[0] = 1.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("MNU3 ARROW DOWN GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 310.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_pineapple_off");
        a.uva[0] = 1.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("MNU3 ARROW DOWN UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 160.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI1"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 170.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI2"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 180.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI3"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 190.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI4"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 200.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI5"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 210.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI6"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 220.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI7"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 230.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI8"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 240.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI9"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 250.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 260.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI11"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 270.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI12"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 280.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI13"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 290.0f, 1.0f };
        p.Begin('UI  ', H("MNU3 LEVEL OFF UI14"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_2");
        p.Begin('UI  ', H("MNU3 BLUE ALPHA 2 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 2 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 2 BAMBOO UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 160.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI1"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI1"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI1"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI1"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 1"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 1"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 170.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI2"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI1"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 2"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 2"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 180.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI3"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI2"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 3"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 3"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 190.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI4"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI3"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 4"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 4"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 200.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI5"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI4"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 5"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 5"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 210.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI6"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI5"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 6"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 6"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 220.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI7"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI6"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 7"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 7"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 230.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI8"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI7"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 8"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 8"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 240.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI9"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI8"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 9"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 9"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 250.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI10"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI9"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 10"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 10"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 260.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI11"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI10"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 11"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 11"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 270.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI12"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI11"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 12"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 12"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 280.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI13"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI14"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI12"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 13"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 13"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 290.0f, 0.0f };
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("MNU3 LEVEL ON UI14"), a);
        p.Link(eEventUISelect, eEventVisible, H("MNU3 LEVEL ON UI14"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 LEVEL ON UI14"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("MNU3 LEVEL ON UI14"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("MNU3 LEVEL ON UI13"));
        p.Link(eEventUISelect, eEventVisible, H("MNU3 PAUSE LEVEL UIF 14"));
        p.Link(eEventUIUnselect, eEventInvisible, H("MNU3 PAUSE LEVEL UIF 14"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 130.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 01"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 180.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 02"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 230.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 03"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 04"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 05"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 06"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 07"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 190.0f, 1.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_grey");
        p.Begin('UI  ', H("MNU3 TASK UI 08"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 130.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 01"), a);
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 01"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 02"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 01"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 180.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 02"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 02"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 01"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 02"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 03"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 02"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 02"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 230.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 03"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 03"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 02"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 03"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 04"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 03"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 03"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 04"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 04"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 03"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 04"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 05"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 04"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 04"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 05"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 05"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 04"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 05"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 06"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 05"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 05"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 06"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 06"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 05"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 06"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 07"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 06"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 06"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 07"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 07"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 06"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 07"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 08"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 07"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 07"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 190.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_spatula_bubble");
        p.Begin('UI  ', H("MNU3 TASK GLOW UI 08"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("MNU3 TASK GLOW UI 08"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("MNU3 TASK GLOW UI 07"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("MNU3 PAUSE TASK UIF 08"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("MNU3 PAUSE TASK UIF 08"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_1");
        p.Begin('UI  ', H("MNU3 BLUE ALPHA 1 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 1 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 1 BAMBOO UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_0");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 0"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 300.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_1");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 1"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 320.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_2");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 2"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 340.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_3");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 3"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 360.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_4");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 4"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 140.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_5");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 5"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 400.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_6");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 6"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 420.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_7");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 7"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 440.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_8");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 8"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 460.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_9");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 9"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_10");
        p.Begin('UI  ', H("MNU3 CONTROL VALUE UI 10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_3");
        p.Begin('UI  ', H("MNU3 BLUE ALPHA 3 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 3 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 3 BAMBOO UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 220.0f, 130.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_house_squidward");
        p.Begin('UI  ', H("MNU3 HOUSE SQUIDWARD UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 520.0f, 130.0f, 1.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_house_spongebob");
        p.Begin('UI  ', H("MNU3 HOUSE SPONGEBOB UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 50.0f, 2.0f };
        a.scale = xVec3{ 1.1f, 0.4f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("MNU3_KABLAM ANIM LIST");
        a.dim[0] = 260; a.dim[1] = 100;
        a.textureID = 0;
        p.Begin('UI  ', H("MNU3 KABLAM UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 50.0f, 2.0f };
        a.scale = xVec3{ -1.1f, 0.4f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("MNU3_KABLAM ANIM LIST");
        a.dim[0] = 260; a.dim[1] = 100;
        a.textureID = 0;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("MNU3 KABLAM 2 UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 0"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 1"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 2"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 350.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 3"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 4"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 390.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 5"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 410.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 6"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 7"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 450.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 8"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 9"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 490.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("MNU3 CONTROL HASH UI 10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 0"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 0"));
        p.Link(eEventVisible, eEventVisible, H("MNU3 KABLAM OFF UI"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 0"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 KABLAM OFF UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 1"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 1"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 1"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 2"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 2"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 2"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 350.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 3"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 3"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 3"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 4"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 4"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 4"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 390.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 5"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 5"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 5"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 410.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 6"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 6"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 6"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 7"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 7"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 7"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 450.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 8"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 8"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 8"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 9"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 9"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 9"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 490.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("MNU3 CONTROL HASH B UI 10"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU3 CONTROL VALUE UI 10"));
        p.Link(eEventVisible, eEventVisible, H("MNU3 KABLAM ON UI"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 CONTROL VALUE UI 10"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU3 KABLAM ON UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 200.0f, 3.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_arrowup");
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 1.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 0.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("MNU3 CONTROL OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 200.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_arrowup_glow");
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 1.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 0.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("MNU3 CONTROL OFF GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 200.0f, 3.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_arrowup");
        a.uva[0] = 0.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 1.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("MNU3 CONTROL ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 200.0f, 2.0f };
        a.dim[0] = 50; a.dim[1] = 50;
        a.textureID = H("ui_arrowup_glow");
        a.uva[0] = 0.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 1.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("MNU3 CONTROL ON GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 225.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.2f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("MNU3_KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = 0;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("MNU3 KABLAM OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 523.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.2f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("MNU3_KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = 0;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("MNU3 KABLAM ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 190.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_iconsb_0");
        p.Begin('UI  ', H("MNU3 CONTROL SB OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 190.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_iconsb_10");
        p.Begin('UI  ', H("MNU3 CONTROL SB ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 250.0f, 50.0f, 80.0f };
        a.dim[0] = 360; a.dim[1] = 320;
        a.textureID = H("battle_for_bikini4");
        p.Begin('UI  ', H("MNU3 TITLE CARD UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 430.0f, 180.0f, 0.0f };
        a.dim[0] = 128; a.dim[1] = 128;
        a.textureID = 0;
        p.Begin('UI  ', H("MNU3 THUMBICON"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x1D;
        a.moreFlags = 0;
        a.surfaceID = H("MNU3_CAUSTICS SURFACE");
        a.pos = xVec3{ 220.0f, 140.0f, 0.0f };
        a.scale = xVec3{ 3.4f, 2.6f, 0.0f };
        a.modelInfoID = H("ui_3dicon_caustics");
        a.dim[0] = 200; a.dim[1] = 200;
        a.textureID = 0;
        p.Begin('UI  ', H("AAA CAUSTICS SURFACE UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x1D;
        a.moreFlags = 0;
        a.surfaceID = H("MNU3_INTRO SURFACE");
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 220.0f, 140.0f, 0.0f };
        a.scale = xVec3{ 3.4f, 2.6f, 0.1f };
        a.modelInfoID = H("ui_3dicon_intro_01");
        a.dim[0] = 200; a.dim[1] = 200;
        a.textureID = 0;
        p.Begin('UI  ', H("AAA INTRO SURFACE UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 50.0f, 50.0f, 80.0f };
        a.dim[0] = 540; a.dim[1] = 380;
        a.textureID = H("title_heavy_iron");
        p.Begin('UI  ', H("MNU3 TITLE CARD HI UI"), a);
        p.End();
    }
}
