// Generated by tools/menugen/menugen.py from the Xbox mnu3.HIP, then kept by
// hand. This file is the source of MNU3's text now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

void MNU3_BuildText(iAssetPkg& p)
{
    p.Text(H("LD ACCESS HARD DISK? TXT"), "Press {i:button_picture_01} to access Xbox Hard Disk");
    p.Text(H("LD ACCESSING HARD DISK TXT"), "Accessing Xbox Hard Disk...");
    p.Text(H("LD DAMAGED SAVE GAME TXT"), "{c=ffff0000}Load failed!{~:c}{n}The data could not be loaded correctly!{n}Check {i:PS2_MEMCARD} in memory card slot {var:MCSelectedCard} and please try again.");
    p.Text(H("MAIN MENU TXT"), "Main Menu");
    p.Text(H("MNU3  CIRCLE TXT"), "{i:ui_options}");
    p.Text(H("MNU3  CREDITS TXT"), "Credits");
    p.Text(H("MNU3  D-PAD ADJUST TXT"), "{c=ff646464}{~:c}< > Adjust");
    p.Text(H("MNU3  MAX TXT"), "Max!");
    p.Text(H("MNU3  MIN TXT"), "Min");
    p.Text(H("MNU3  MONO TXT"), "Mono");
    p.Text(H("MNU3  MUSIC TITLE TXT"), "Music Volume");
    p.Text(H("MNU3  MUSIC VOL NUM TXT"), "{var:SoundMusicVolume}");
    p.Text(H("MNU3  MUSIC VOL TXT"), "Music{n}Volume");
    p.Text(H("MNU3  NEW GAME TXT"), "New Game");
    p.Text(H("MNU3  NO TXT"), "No");
    p.Text(H("MNU3  OFF TXT"), "Off");
    p.Text(H("MNU3  ON TXT"), "On");
    p.Text(H("MNU3  OPTIONS SCREEN TXT"), "Use the directional buttons to adjust the screen position.");
    p.Text(H("MNU3  PAUSE OPTIONS LOAD  TXT"), "Load Game");
    p.Text(H("MNU3  SCREEN ACCEPT TXT"), "{i:ui_accept} Accept");
    p.Text(H("MNU3  SCREEN ADJUST TXT"), "Screen{n}Adjust");
    p.Text(H("MNU3  SCREEN CANCEL TXT"), "{i:ui_cancel} Cancel");
    p.Text(H("MNU3  SCREEN INF TXT"), "Use the Left Analog Stick or directional buttons to adjust the screen.");
    p.Text(H("MNU3  SCREEN RESET TXT"), "{i:ui_options} Reset");
    p.Text(H("MNU3  SCREEN TITLE TXT"), "Screen Adjust");
    p.Text(H("MNU3  SFX TITLE TXT"), "SFX Volume");
    p.Text(H("MNU3  SFX VOL NUM TXT"), "{var:SoundFXVolume}");
    p.Text(H("MNU3  SFX VOL TXT"), "SFX{n}Volume");
    p.Text(H("MNU3  SOUND MODE TXT"), "Sound{n}Mode");
    p.Text(H("MNU3  SOUND TITLE TXT"), "Sound Mode");
    p.Text(H("MNU3  SQUARE TXT"), "{i:ui_misc}");
    p.Text(H("MNU3  STEREO TXT"), "Stereo");
    p.Text(H("MNU3  TRI BACK TXT"), "{i:ui_cancel} Return");
    p.Text(H("MNU3  TRI TXT"), "{i:ui_cancel}");
    p.Text(H("MNU3  VIBE MODE TXT"), "Vibration{n}Mode");
    p.Text(H("MNU3  VIBE TITLE TXT"), "Vibration Mode");
    p.Text(H("MNU3  X CHOOSE TXT"), "{i:ui_accept} Choose");
    p.Text(H("MNU3  X TXT"), "{i:ui_accept}");
    p.Text(H("MNU3  YES TXT"), "Yes");
    p.Text(H("MNU3 CANT CREATE A NEW GAME TXT"), "No {i:PS2_MEMCARD} was found. Please insert a {i:PS2_MEMCARD}.");
    p.Text(H("MNU3 CONTINUE TXT"), "{i:ui_accept} Continue");
    p.Text(H("MNU3 CONTROLS MUSIC VOL TXT"), "Music Volume");
    p.Text(H("MNU3 CONTROLS SFX VOL TXT"), "SFX Volume");
    p.Text(H("MNU3 CONTROLS SOUND MODE TXT"), "Sound Mode");
    p.Text(H("MNU3 CONTROLS VIBE MODE TXT"), "Vibration Mode");
    p.Text(H("MNU3 CREATE A NEW GAME NO TXT"), "No");
    p.Text(H("MNU3 CREATE A NEW GAME PAL TXT"), "Would you like to create a game file to save your progress?{n}{n}(The game uses autosave feature. While playing, Do not remove {i:PS2_MEMCARD}, or the {i:PS2_PAD_PAL}, or reset/switch off the console.)");
    p.Text(H("MNU3 CREATE A NEW GAME TXT"), "{n}{n}The game uses an autosave feature.{n}While playing, please do not turn off your Xbox console.{n}Would you like to create a save game to save your progress?");
    p.Text(H("MNU3 CREATE A NEW GAME YES TXT"), "Yes");
    p.Text(H("MNU3 EXTRAS TXT"), "Extras");
    p.Text(H("MNU3 FREE DISK TEXT"), "Available Free Block(s): {var:SpaceAvailableString} block(s)");
    p.Text(H("MNU3 INTENTIONALLY BLANK TXT"), "");
    p.Text(H("MNU3 LEVEL TXT 1"), "Bikini Bottom");
    p.Text(H("MNU3 LEVEL TXT 10"), "Kelp Forest");
    p.Text(H("MNU3 LEVEL TXT 11"), "Flying Dutchman's Graveyard");
    p.Text(H("MNU3 LEVEL TXT 12"), "Spongebob's Dream");
    p.Text(H("MNU3 LEVEL TXT 13"), "Chum Bucket Lab");
    p.Text(H("MNU3 LEVEL TXT 14"), "Glove World");
    p.Text(H("MNU3 LEVEL TXT 2"), "Jellyfish Fields");
    p.Text(H("MNU3 LEVEL TXT 3"), "Downtown Bikini Bottom");
    p.Text(H("MNU3 LEVEL TXT 4"), "Goo Lagoon");
    p.Text(H("MNU3 LEVEL TXT 5"), "Poseidome");
    p.Text(H("MNU3 LEVEL TXT 6"), "Rock Bottom");
    p.Text(H("MNU3 LEVEL TXT 7"), "Mermalair");
    p.Text(H("MNU3 LEVEL TXT 8"), "Sand Mountain");
    p.Text(H("MNU3 LEVEL TXT 9"), "Industrial Park");
    p.Text(H("MNU3 PAUSE OPTIONS CONTROLS TXT"), "Options");
    p.Text(H("MNU3 PRESS START TXT"), "Press START{n}Button");
    p.Text(H("MNU3 PROMO TITLE TXT 00"), "Fairly Oddparents!: Breakin' Da Rules");
    p.Text(H("MNU3 PROMO TITLE TXT 01"), "Tak and the Power of Juju");
    p.Text(H("MNU3 PROMO TITLE TXT 02"), "Jimmy Neutron: Jet Fusion");
    p.Text(H("MNU3 PROMO TITLE TXT 03"), "Paramount DVD/VHS Preview");
    p.Text(H("MNU3 RETRY TXT"), "{i:ui_accept} Retry");
    p.Text(H("MNU3 TASK TXT 01"), "Complete task numero uno.");
    p.Text(H("MNU3 TASK TXT 02"), "complete task numero dos.");
    p.Text(H("MNU3 TASK TXT 03"), "complete task numero tres.");
    p.Text(H("MNU3 TASK TXT 04"), "complete task numero quatro.");
    p.Text(H("MNU3 TASK TXT 05"), "complete task numero cinco.");
    p.Text(H("MNU3 TASK TXT 06"), "complete task numero seis.");
    p.Text(H("MNU3 TASK TXT 07"), "complete task numero siete.");
    p.Text(H("MNU3 TASK TXT 08"), "complete task numero ocho.");
    p.Text(H("SCREEN PRESS X TXT"), "{i:ui_options} Adjust");
}
