// Generated by tools/menugen/menugen.py from the Xbox mnu4.HIP, then kept by
// hand. This file is the source of MNU4's text now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

void MNU4_BuildText(iAssetPkg& p)
{
    p.Text(H("CIRCLE TXT"), "{i:ui_options}");
    p.Text(H("COMBO_01_TXT"), "Combo!");
    p.Text(H("COMBO_02_TXT"), "Super Combo!");
    p.Text(H("COMBO_03_TXT"), "Ultra Combo!");
    p.Text(H("COMBO_04_TXT"), "Super-Ultra Combo!");
    p.Text(H("COMBO_05_TXT"), "Mega Combo!");
    p.Text(H("COMBO_06_TXT"), "Super-Mega Combo!");
    p.Text(H("COMBO_07_TXT"), "Super-Ultra-Mega Combo!");
    p.Text(H("COMBO_08_TXT"), "Monster Combo!");
    p.Text(H("COMBO_09_TXT"), "Super-Monster Combo!");
    p.Text(H("COMBO_10_TXT"), "Ultra-Monster Combo!");
    p.Text(H("COMBO_11_TXT"), "Mega-Monster Combo!");
    p.Text(H("COMBO_12_TXT"), "Super-Ultra-Monster Combo!");
    p.Text(H("COMBO_13_TXT"), "Super-Ultra-Mega-Monster Combo!");
    p.Text(H("CONTROLLER MISSING TEXT"), "Please reconnect controller to port {var:ActivePad} and press START to continue");
    p.Text(H("CONTROLS MUSIC VOLUME TXT"), "Music Volume");
    p.Text(H("CONTROLS SFX VOLUME TXT"), "SFX Volume");
    p.Text(H("CONTROLS SOUND MODE TXT"), "Sound Mode");
    p.Text(H("CONTROLS VIBRATION MODE TXT"), "Vibration Mode");
    p.Text(H("CURRENTDATE TXT"), "{var:CurrentDate}");
    p.Text(H("CURRENTTIME TXT"), "{var:CurrentTime}");
    p.Text(H("INTENTIONALLY BLANK TXT"), "");
    p.Text(H("LD BADFORMAT TXT"),
           "{c=ffff0000}Save failed!{~:c}{n}The save folder could not be written to.{n}Press "
           "{i:ui_accept} to continue.");
    p.Text(H("LD BADLOAD TXT"), "{c=ffff0000}Load failed!{~:c} Unable to load game. Press {i:ui_accept} to continue");
    p.Text(H("LD ERR NOCARD TXT"), "No save folder was found.");
    p.Text(H("LD ERR NOGAME TXT"), "No SpongeBob games were found.");
    p.Text(H("LD FORMAT PROMPT TXT"), "Your save folder is not ready.{n}{n}Do you wish to create it?");
    p.Text(H("LD FORMATCONFIRM TXT"), "Are you sure you wish to create your save folder?  Press {i:ui_accept} to confirm.");
    p.Text(H("LD GAMESLOT 0 TXT"), "{var:GameSlot0}");
    p.Text(H("LD GAMESLOT 1 TXT"), "{var:GameSlot1}");
    p.Text(H("LD GAMESLOT 2 TXT"), "{var:GameSlot2}");
    p.Text(H("LD GAMESLOT 3 TXT"), "{var:GameSlot3}");
    p.TextSpace(H("LD LOAD GAME TXT"), "Load saved game", 64);
    p.Text(H("LD MC DONTREMOVE PAL TXT"), "WARNING: {var:MCAccessType}...{n}Do not close the game while it is saving.");
    p.Text(H("LD MC DONTREMOVE TXT"), "Loading Game.....{n}Please wait.");
    p.Text(H("LD MC MISSING TXT"), "The save folder could not be opened.");
    p.Text(H("LD MC1 TXT"), "save folder");
    p.Text(H("LD MC2 TXT"), "second save folder");
    p.Text(H("LD NOGAME TXT"), "No save file exists.");
    p.Text(H("LD NOGAMES TXT"), "No saved games were found.");
    p.Text(H("LEVEL TXT 1"), "Bikini Bottom");
    p.Text(H("LEVEL TXT 10"), "Kelp Forest");
    p.Text(H("LEVEL TXT 11"), "Flying Dutchman's Graveyard");
    p.Text(H("LEVEL TXT 12"), "Spongebob's Dream");
    p.Text(H("LEVEL TXT 13"), "Chum Bucket Lab");
    p.Text(H("LEVEL TXT 14"), "Patrick");
    p.Text(H("LEVEL TXT 15"), "Mr. Krabs");
    p.Text(H("LEVEL TXT 2"), "Jellyfish Fields");
    p.Text(H("LEVEL TXT 3"), "Downtown Bikini Bottom");
    p.Text(H("LEVEL TXT 4"), "Goo Lagoon");
    p.Text(H("LEVEL TXT 5"), "Poseidome");
    p.Text(H("LEVEL TXT 6"), "Rock Bottom");
    p.Text(H("LEVEL TXT 7"), "Mermalair");
    p.Text(H("LEVEL TXT 8"), "Sand Mountain");
    p.Text(H("LEVEL TXT 9"), "Industrial Park");
    p.Text(H("MAX TXT"), "Max!");
    p.Text(H("MIN TXT"), "Min");
    p.Text(H("MNIU4 NPCTALK TXT"), "Pull the {i:button_talktonpc_text} to Talk");
    p.Text(H("MNU3 CREDITS TXT"), "Credits");
    p.Text(H("MNU3 NEW GAME TXT"), "New Game");
    p.Text(H("MNU3 PROMOTIONAL MATERIALS TXT"), "Promo Materials");
    p.Text(H("MNU4 AUTO SAVE CHANGED TXT"),
           "{i:keyword}Data could not be autosaved correctly!{~:c}{n}Your save folder has "
           "{i:keyword}changed{~:c}. The {i:autosave} feature has been {i:keyword}disabled{~:c}. "
           "{i:blacktext}To re-enable {i:autosave}, go to {red=0}{blue=0}{green=0.2}Options{~:c} in "
           "the {red=0}{blue=0}{green=0.2}Pause Menu{~:c} and save to a save game file.{n}Press "
           "{i:ui_accept} to continue without saving.");
    p.Text(H("MNU4 AUTO SAVE FAILED NOSPACE TXT"),
           "{i:keyword}Data could not be autosaved correctly!{~:c}{n}There is not enough free space "
           "to save. The {i:autosave} feature has been {i:keyword}disabled{~:c}. {i:blacktext}To "
           "re-enable {i:autosave}, go to {red=0}{blue=0}{green=0.2}Options{~:c} in the "
           "{red=0}{blue=0}{green=0.2}Pause Menu{~:c} and save to a save game file.{n}Press "
           "{i:ui_accept} to continue without saving.");
    p.Text(H("MNU4 AUTO SAVE FAILED TXT"),
           "{i:keyword}Warning: Autosave failed! {~:c}{n}There is not enough free space to create a "
           "new save game. The {i:autosave}{i:blacktext} feature has been {i:keyword}disabled{~:c}. "
           "{i:blacktext}To re-enable {i:autosave}{i:blacktext}, go to the "
           "{red=0}{blue=0}{green=0.2}Options{~:c}{i:blacktext} in the "
           "{red=0}{blue=0}{green=0.2}Pause Menu{~:c}{i:blacktext} and save to a game save.");
    p.Text(H("MNU4 AUTO SAVE FAILED UNFORMATTED TXT"),
           "{i:keyword}Data could not be autosaved correctly!{~:c}{n}Your save folder is not "
           "{i:keyword}ready{~:c}. The {i:autosave} feature has been {i:keyword}disabled{~:c}. "
           "{i:blacktext}To re-enable {i:autosave}, go to {red=0}{blue=0}{green=0.2}Options{~:c} in "
           "the {red=0}{blue=0}{green=0.2}Pause Menu{~:c} and save to a save game file.{n}Press "
           "{i:ui_accept} to continue without saving.");
    p.Text(H("MNU4 AUTO SAVE PAL TXT"),
           "{red=.3}{blue=0}{green=0}Autosaving Data...{~:c}{n}{n}Do not close the game while it is "
           "saving.");
    p.Text(H("MNU4 AUTO SAVE TXT"), "Please do not close the game while it is saving.");
    p.Text(H("MNU4 BUSSTOP TXT"), "Pull the {i:button_exitlevel_text} to switch characters");
    p.Text(H("MNU4 D-PAD ADJUST TXT"), "{c=ff646464}{~:c}< > Adjust");
    p.Text(H("MNU4 EXIT GAME NO TXT"), "No");
    p.Text(H("MNU4 EXIT GAME PROMPT TXT"), "Quit Game and lose all unsaved game data ?");
    p.Text(H("MNU4 EXIT GAME YES TXT"), "Yes");
    p.Text(H("MNU4 FREE DISK TEXT"), "Available Free Space: {var:SpaceAvailableString}");
    p.Text(H("MNU4 OPTIONS SCREEN TXT"), "Screen Adjust");
    p.Text(H("MNU4 SAVE COMPLETED TXT"), "Save Completed!");
    p.Text(H("MNU4 SCREEN ACCEPT TXT"), "{i:button_picture_01} Accept");
    p.Text(H("MNU4 SCREEN CANCEL TXT"), "{i:button_picture_03} Cancel");
    p.Text(H("MNU4 SCREEN INF TXT"), "Use the Left Analog Stick or directional buttons to adjust the screen.");
    p.Text(H("MNU4 SCREEN PRESS X TXT"), "{i:ui_options} Adjust");
    p.Text(H("MNU4 SCREEN RESET TXT"), "{i:button_picture_04} Reset");
    p.Text(H("MNU4 TELEPORT BOX TXT"), "You may use this teleport box once both boxes have been opened up.");
    p.Text(H("MNU4 TRI BACK TXT"), "{i:ui_cancel} Return");
    p.Text(H("MNU4 X CHOOSE TXT"), "{i:ui_accept} Choose");
    p.Text(H("MONO TXT"), "Mono");
    p.Text(H("MUSIC TITLE TXT"), "Music Volume");
    p.Text(H("MUSIC VOL NUM TXT"), "{var:SoundMusicVolume}");
    p.Text(H("MUSIC VOLUME TXT"), "Music{n}Volume");
    p.Text(H("NO TXT"), "No");
    p.Text(H("OFF TXT"), "Off");
    p.Text(H("ON TXT"), "On");
    p.Text(H("PAUSE BUS TXT"), "{i:ui_accept} Take the taxi");
    p.Text(H("PAUSE GAME PAUSED TXT"), "Game Paused");
    p.Text(H("PAUSE OPTIONS CONTROLS TXT"), "Adjust Settings");
    p.Text(H("PAUSE OPTIONS EXIT LEVEL TXT"), "Exit {var:CurrentScene}");
    p.Text(H("PAUSE OPTIONS LOAD TXT"), "Load Game");
    p.Text(H("PAUSE OPTIONS QUIT TXT"), "Quit Game");
    p.Text(H("PAUSE OPTIONS RETURN TXT"), "Return to previous menu");
    p.Text(H("PAUSE OPTIONS SAVE TXT"), "Save Game");
    p.Text(H("PAUSE OPTIONS TXT"), "{i:ui_options} Options");
    p.Text(H("PAUSE RETURN GAME TXT"), "{i:ui_cancel} Return to Game");
    p.Text(H("PAUSE TASK TXT 0101"), "On Top of the Pineapple");
    p.Text(H("PAUSE TASK TXT 0102"), "On Top of Shady Shoals");
    p.Text(H("PAUSE TASK TXT 0103"), "On Top of the Chum Bucket");
    p.Text(H("PAUSE TASK TXT 0104"), "SpongeBob's Closet");
    p.Text(H("PAUSE TASK TXT 0105"), "Annoy Squidward");
    p.Text(H("PAUSE TASK TXT 0106"), "Ambush at the Tree Dome");
    p.Text(H("PAUSE TASK TXT 0107"), "Infestation at the Krusty Krab");
    p.Text(H("PAUSE TASK TXT 0108"), "A Wall Jump in the Bucket");
    p.Text(H("PAUSE TASK TXT 0201"), "Top of the hill");
    p.Text(H("PAUSE TASK TXT 0202"), "Cowa-Bungee!");
    p.Text(H("PAUSE TASK TXT 0203"), "Spelunking");
    p.Text(H("PAUSE TASK TXT 0204"), "Patrick's Dilemma");
    p.Text(H("PAUSE TASK TXT 0205"), "Navigate the Canyons and Mesas");
    p.Text(H("PAUSE TASK TXT 0206"), "Drain the Lake");
    p.Text(H("PAUSE TASK TXT 0207"), "Slide Leap");
    p.Text(H("PAUSE TASK TXT 0208"), "Defeat King Jellyfish");
    p.Text(H("PAUSE TASK TXT 0301"), "End of the Road");
    p.Text(H("PAUSE TASK TXT 0302"), "Learn Sandy's Moves");
    p.Text(H("PAUSE TASK TXT 0303"), "Tikis Go Boom");
    p.Text(H("PAUSE TASK TXT 0304"), "Across the Rooftops");
    p.Text(H("PAUSE TASK TXT 0305"), "Swingin' Sandy");
    p.Text(H("PAUSE TASK TXT 0306"), "Ambush in the Lighthouse");
    p.Text(H("PAUSE TASK TXT 0307"), "Extreme Bungee");
    p.Text(H("PAUSE TASK TXT 0308"), "Come Back With the Cruise Bubble");
    p.Text(H("PAUSE TASK TXT 0401"), "King of the Castle");
    p.Text(H("PAUSE TASK TXT 0402"), "Connect the Towers");
    p.Text(H("PAUSE TASK TXT 0403"), "Save the Children");
    p.Text(H("PAUSE TASK TXT 0404"), "Over the Moat");
    p.Text(H("PAUSE TASK TXT 0405"), "Through the Sea Caves");
    p.Text(H("PAUSE TASK TXT 0406"), "Clean out the Bumper Boats");
    p.Text(H("PAUSE TASK TXT 0407"), "Slip and Slide Under the Pier");
    p.Text(H("PAUSE TASK TXT 0408"), "Tower Bungee");
    p.Text(H("PAUSE TASK TXT 0501"), "Rumble At the Poseidome");
    p.Text(H("PAUSE TASK TXT 0601"), "Get to the Museum");
    p.Text(H("PAUSE TASK TXT 0602"), "Slip Sliding Away");
    p.Text(H("PAUSE TASK TXT 0603"), "Return the Museum's Art");
    p.Text(H("PAUSE TASK TXT 0604"), "Swingalong Spatula");
    p.Text(H("PAUSE TASK TXT 0605"), "Plundering Robots in the Museum");
    p.Text(H("PAUSE TASK TXT 0606"), "Across the Trench of Darkness");
    p.Text(H("PAUSE TASK TXT 0607"), "Lasers are Fun and Good for You");
    p.Text(H("PAUSE TASK TXT 0608"), "How in Tarnation Do You Get There?");
    p.Text(H("PAUSE TASK TXT 0701"), "Top of the Entrance Area");
    p.Text(H("PAUSE TASK TXT 0702"), "Top of the Computer Area");
    p.Text(H("PAUSE TASK TXT 0703"), "Shut Down the Security System");
    p.Text(H("PAUSE TASK TXT 0704"), "The Funnel Machines");
    p.Text(H("PAUSE TASK TXT 0705"), "The Spinning Towers of Power");
    p.Text(H("PAUSE TASK TXT 0706"), "Top of the Security Tunnel");
    p.Text(H("PAUSE TASK TXT 0707"), "Complete the Rolling Ball Room");
    p.Text(H("PAUSE TASK TXT 0708"), "Defeat Prawn");
    p.Text(H("PAUSE TASK TXT 0801"), "Frosty Bungee");
    p.Text(H("PAUSE TASK TXT 0802"), "Top of the Lodge");
    p.Text(H("PAUSE TASK TXT 0803"), "Defeat Robots on Guppy Mound");
    p.Text(H("PAUSE TASK TXT 0804"), "Beat Mrs. Puff's Time");
    p.Text(H("PAUSE TASK TXT 0805"), "Defeat Robots on Flounder Hill");
    p.Text(H("PAUSE TASK TXT 0806"), "Beat Bubble Buddy's Time");
    p.Text(H("PAUSE TASK TXT 0807"), "Defeat Robots on Sand Mountain");
    p.Text(H("PAUSE TASK TXT 0808"), "Beat Larry's Time");
    p.Text(H("PAUSE TASK TXT 0901"), "Robo-Patrick Ahoy!");
    p.Text(H("PAUSE TASK TXT 1001"), "Through the Woods");
    p.Text(H("PAUSE TASK TXT 1002"), "Find all the Lost Campers");
    p.Text(H("PAUSE TASK TXT 1003"), "Tiki Roundup");
    p.Text(H("PAUSE TASK TXT 1004"), "Down in the Swamp");
    p.Text(H("PAUSE TASK TXT 1005"), "Through the Kelp Caves");
    p.Text(H("PAUSE TASK TXT 1006"), "Power Crystal Crisis");
    p.Text(H("PAUSE TASK TXT 1007"), "Kelp Vine Slide");
    p.Text(H("PAUSE TASK TXT 1008"), "Beat Mermaid Man's Time");
    p.Text(H("PAUSE TASK TXT 1101"), "Top of the Entrance Area");
    p.Text(H("PAUSE TASK TXT 1102"), "A Path Through the Goo");
    p.Text(H("PAUSE TASK TXT 1103"), "Goo Tanker Ahoy!");
    p.Text(H("PAUSE TASK TXT 1104"), "Top of the Stack of Ships");
    p.Text(H("PAUSE TASK TXT 1105"), "Shipwreck Bungee");
    p.Text(H("PAUSE TASK TXT 1106"), "Destroy the Robot Ship");
    p.Text(H("PAUSE TASK TXT 1107"), "Get Aloft There, Matey!");
    p.Text(H("PAUSE TASK TXT 1108"), "Defeat the Flying Dutchman");
    p.Text(H("PAUSE TASK TXT 1201"), "Across the Dreamscape");
    p.Text(H("PAUSE TASK TXT 1202"), "Follow the Bouncing Ball");
    p.Text(H("PAUSE TASK TXT 1203"), "Slidin' Texas Style");
    p.Text(H("PAUSE TASK TXT 1204"), "Swingers Ahoy");
    p.Text(H("PAUSE TASK TXT 1205"), "Music is in the Ear of the Beholder");
    p.Text(H("PAUSE TASK TXT 1206"), "Krabby Patty Platforms");
    p.Text(H("PAUSE TASK TXT 1207"), "Super Bounce");
    p.Text(H("PAUSE TASK TXT 1208"), "Here You Go");
    p.Text(H("PAUSE TASK TXT 1301"), "Robo-SpongeBob Musclepants");
    p.Text(H("PAUSE TASK TXT 1302"), "Kah - Rah - Tae!");
    p.Text(H("PAUSE TASK TXT 1303"), "The Small Shall Rule... Or Not");
    p.Text(H("PAUSE TASK TXT 1401"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1402"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1403"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1404"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1405"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1406"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1407"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1408"), "Return 10 Socks to Patrick");
    p.Text(H("PAUSE TASK TXT 1501"), "Pay Mr. Krabs 3,000 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1502"), "Pay Mr. Krabs 3,500 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1503"), "Pay Mr. Krabs 4,000 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1504"), "Pay Mr. Krabs 4,500 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1505"), "Pay Mr. Krabs 5,000 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1506"), "Pay Mr. Krabs 5,500 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1507"), "Pay Mr. Krabs 6,500 Shiny Objects");
    p.Text(H("PAUSE TASK TXT 1508"), "Pay Mr. Krabs 7,500 Shiny Objects");
    p.Text(H("PAUSE TASK TXT none"), "You have not received this task");
    p.Text(H("PS2_MEMCARD"), "save folder");
    p.Text(H("PS2_NAME"), HOST_NAME);
    p.Text(H("PS2_PAD"), "controller");
    p.Text(H("PS2_PAD_PAL"), "controller");
    p.TextSpace(H("SAVE GAME TXT"), "Save Game", 64);
    p.Text(H("SCREEN ADJUST TXT"), "Screen{n}Adjust");
    p.Text(H("SCREEN TITLE TXT"), "Screen Adjust");
    p.Text(H("SFX TITLE TXT"), "SFX Volume");
    p.Text(H("SFX VOL NUM TXT"), "{var:SoundFXVolume}");
    p.Text(H("SFX VOLUME TXT"), "SFX{n}Volume");
    p.Text(H("SOUND MODE TXT"), "Sound{n}Mode");
    p.Text(H("SOUND TITLE TXT"), "Sound Mode");
    p.Text(H("SQUARE TXT"), "{i:ui_misc}");
    p.Text(H("STEREO TXT"), "Stereo");
    p.Text(H("SV BADSAVE TXT"),
           "{c=ffff0000}Save failed!{~:c} There is not enough free space to create new save games. "
           "Press {i:ui_accept} to continue.");
    p.Text(H("SV FORMAT CONFIRM TXT"), "Are you sure you wish to create your save folder?");
    p.Text(H("SV MC DONTREMOVE PAL TXT"), "WARNING: {var:MCAccessType}...{n}Do not close the game while it is saving.");
    p.Text(H("SV MC DONTREMOVE TXT"), "Saving Game.....{n}Do not close the game while it is saving.");
    p.Text(H("SV NOSPACE TXT"),
           "There is not enough free space to create new save games. Press {i:ui_accept} to "
           "continue.");
    p.Text(H("SV NOSPACEGAME TXT"), "There is not enough space to save your game.");
    p.Text(H("SV OVERWRITE TXT"), "A game already exists. Would you like to overwrite it?");
    p.Text(H("SV RETRY TXT"), "{i:ui_accept} Retry");
    p.Text(H("TASK TXT 01"), "Complete task numero uno.");
    p.Text(H("TASK TXT 02"), "complete task numero dos.");
    p.Text(H("TASK TXT 03"), "complete task numero tres.");
    p.Text(H("TASK TXT 04"), "complete task numero quatro.");
    p.Text(H("TASK TXT 05"), "complete task numero cinco.");
    p.Text(H("TASK TXT 06"), "complete task numero seis.");
    p.Text(H("TASK TXT 07"), "complete task numero siete.");
    p.Text(H("TASK TXT 08"), "complete task numero ocho.");
    p.Text(H("TASK TXT B101"), "Defeat Sandy BossBot");
    p.Text(H("TASK TXT B201"), "Defeat Patrick BossBot");
    p.Text(H("TASK TXT B301"), "Defeat Spongebob BossBot");
    p.Text(H("TASK TXT BB01"), "End of the Road");
    p.Text(H("TASK TXT BB02"), "Learn Sandy's Moves");
    p.Text(H("TASK TXT BB03"), "Tikis Go Boom");
    p.Text(H("TASK TXT BB04"), "Across the Rooftops");
    p.Text(H("TASK TXT BB05"), "Swingin' Sandy");
    p.Text(H("TASK TXT BB06"), "Ambush in the lighthouse");
    p.Text(H("TASK TXT BB07"), "Extreme Bungee");
    p.Text(H("TASK TXT BB08"), "Come Back With the Cruise Bubble");
    p.Text(H("TASK TXT BC01"), "Top of the Entrance Area");
    p.Text(H("TASK TXT BC02"), "Top of the Computer Area");
    p.Text(H("TASK TXT BC03"), "Shut Down the Security System");
    p.Text(H("TASK TXT BC04"), "The Funnel Machines");
    p.Text(H("TASK TXT BC05"), "The Spinning Towers of Power");
    p.Text(H("TASK TXT BC06"), "");
    p.Text(H("TASK TXT BC07"), "Complete the Rolling Ball Room");
    p.Text(H("TASK TXT BC08"), "Defeat Prawn");
    p.Text(H("TASK TXT DB01"), "Across the dreamscape");
    p.Text(H("TASK TXT DB02"), "Up, up and away");
    p.Text(H("TASK TXT DB03"), "Slidin' Texas Style");
    p.Text(H("TASK TXT DB04"), "Swingers Ahoy");
    p.Text(H("TASK TXT DB05"), "Krabby Patty Platforms");
    p.Text(H("TASK TXT DB06"), "Music is in the ear of the beholder");
    p.Text(H("TASK TXT DB07"), "Screaming for Ice Cream");
    p.Text(H("TASK TXT DB08"), "Here you go");
    p.Text(H("TASK TXT GL01"), "King of the Castle");
    p.Text(H("TASK TXT GL02"), "Connect the Towers");
    p.Text(H("TASK TXT GL03"), "Save the Children");
    p.Text(H("TASK TXT GL04"), "Over the Moat");
    p.Text(H("TASK TXT GL05"), "Through the Sea Caves");
    p.Text(H("TASK TXT GL06"), "Clean out the Bumper Boats");
    p.Text(H("TASK TXT GL07"), "Slip and Slide under the Pier");
    p.Text(H("TASK TXT GL08"), "Tower Bungee");
    p.Text(H("TASK TXT GY01"), "Top of the Entrance Area");
    p.Text(H("TASK TXT GY02"), "A Path Through the Goo");
    p.Text(H("TASK TXT GY03"), "Goo Tanker Ahoy!");
    p.Text(H("TASK TXT GY04"), "Top of the Stack of Ships");
    p.Text(H("TASK TXT GY05"), "Shipwreck Bungee");
    p.Text(H("TASK TXT GY06"), "Destroy the Robot Ship");
    p.Text(H("TASK TXT GY07"), "Get Aloft There Maty");
    p.Text(H("TASK TXT GY08"), "Defeat the Flying Dutchman");
    p.Text(H("TASK TXT HB01"), "On top of the Pinapple");
    p.Text(H("TASK TXT HB02"), "On top of Shady Shoals");
    p.Text(H("TASK TXT HB03"), "On top of the Chum Bucket");
    p.Text(H("TASK TXT HB04"), "SpongeBob's Closet");
    p.Text(H("TASK TXT HB05"), "Annoy Squidward");
    p.Text(H("TASK TXT HB06"), "Ambush at the Tree Dome");
    p.Text(H("TASK TXT HB07"), "Infestation at the Krusty Krab");
    p.Text(H("TASK TXT HB08"), "A Wall Jump in the Bucket");
    p.Text(H("TASK TXT JF01"), "Top of the hill");
    p.Text(H("TASK TXT JF02"), "Cowa-Bungee!");
    p.Text(H("TASK TXT JF03"), "Spelunking");
    p.Text(H("TASK TXT JF04"), "Patrick's Dilemna");
    p.Text(H("TASK TXT JF05"), "Navigate the Canyons and Mesas");
    p.Text(H("TASK TXT JF06"), "Drain the Lake");
    p.Text(H("TASK TXT JF07"), "Slide Leap");
    p.Text(H("TASK TXT JF08"), "Defeat King Jellyfish");
    p.Text(H("TASK TXT KF01"), "Through the woods");
    p.Text(H("TASK TXT KF02"), "Find all the lost campers");
    p.Text(H("TASK TXT KF03"), "Tiki roundup");
    p.Text(H("TASK TXT KF04"), "Down in the Swamp");
    p.Text(H("TASK TXT KF05"), "Through the kelp Caves");
    p.Text(H("TASK TXT KF06"), "Power Crystal Crisis");
    p.Text(H("TASK TXT KF07"), "Kelp Vine Slide");
    p.Text(H("TASK TXT KF08"), "Beat Mermaid Man's Time");
    p.Text(H("TASK TXT RB01"), "Get to the Museum");
    p.Text(H("TASK TXT RB02"), "Slip Sliding Away");
    p.Text(H("TASK TXT RB03"), "Return the Museum's Art");
    p.Text(H("TASK TXT RB04"), "Leap of Faith from the Slide");
    p.Text(H("TASK TXT RB05"), "Plundering Robots in the Museum");
    p.Text(H("TASK TXT RB06"), "Across the Trench of Darkness");
    p.Text(H("TASK TXT RB07"), "Lasers are fun and good for you");
    p.Text(H("TASK TXT RB08"), "How in tarnation do you get there?");
    p.Text(H("TASK TXT SM01"), "Frosty Bungee");
    p.Text(H("TASK TXT SM02"), "Top of the Lodge");
    p.Text(H("TASK TXT SM03"), "Defeat Robots on Guppy Mound");
    p.Text(H("TASK TXT SM04"), "Beat Mrs. Puff's Time");
    p.Text(H("TASK TXT SM05"), "Defeat Robots on Flounder Hill");
    p.Text(H("TASK TXT SM06"), "Beat Bubble Buddy's Time");
    p.Text(H("TASK TXT SM07"), "Defeat Robots on Sand Mountain");
    p.Text(H("TASK TXT SM08"), "Beat Larry's Time");
    p.Text(H("TAXI CONFIRM TXT"), "Take the taxi to this level?");
    p.Text(H("TAXI NO TXT"), "{i:ui_cancel} No, thanks");
    p.Text(H("TAXI YES TXT"), "{i:ui_accept} Yes");
    p.Text(H("TRI TXT"), "{i:ui_cancel}");
    p.Text(H("VIBRATION MODE TXT"), "Vibration{n}Mode");
    p.Text(H("VIBRATION TITLE TXT"), "Vibration Mode");
    p.Text(H("X TXT"), "{i:ui_accept}");
    p.Text(H("YES TXT"), "Yes");
    p.Text(H("autosave"), "{red=0}{blue=0}{green=0.2}AutoSave{~:c}");
    p.Text(H("ps2_save_text"), "At least {i:keyword}{var:MCPS2MinSpace} KB{~:c} of free space is needed to save game data. Up to {i:keyword}{var:MCPS2MaxSpace} KB{~:c} may be needed to save all three games");
    p.Text(H("text_pause_stall"), "{w*1.5}{h*1.5}{n}Paused{n}");

    // The PC save screen's rows, filled in by iSaveScreen.cpp.
    for (S32 i = 0; i < ISAVESCREEN_ROWS; i++)
    {
        char name[32];
        sprintf(name, ISAVESCREEN_ROW_TEXT, (int)i);
        p.TextSpace(H(name), "", ISAVESCREEN_ROW_TEXT_SIZE);
    }

    // The settings screen (iSettingsScreen.cpp fills these in) and the two
    // menu entries that open it.
    p.Text(H("PC SETTINGS TXT"), "Settings");
    p.TextSpace(H(ISETTINGS_TITLE_TEXT), "Settings", 256);
    p.TextSpace(H(ISETTINGS_HELP_TEXT), "", 256);
    for (S32 i = 0; i < ISETTINGS_ROWS; i++)
    {
        char name[32];
        sprintf(name, ISETTINGS_LABEL_TEXT, (int)i);
        p.TextSpace(H(name), "", 64);
        sprintf(name, ISETTINGS_VALUE_TEXT, (int)i);
        p.TextSpace(H(name), "", 96);
    }
}
