// Generated by tools/menugen/menugen.py from the Xbox mnu4.HIP, then kept by
// hand. This file is the source of MNU4's groups, conditionals, timers,
// dispatchers, sound effects, counters and portals now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static xGroupAsset GroupDefaultsInit()
{
    xGroupAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeGroup;
    a.baseFlags = 0xD;
    return a;
}

static const xGroupAsset kGroupDefaults = GroupDefaultsInit();

void MNU4_BuildGroup(iAssetPkg& p)
{
    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("PAUSE GROUP"), a);
        p.Item(H("PAUSE RETURN GAME UIF"));
        p.Item(H("PAUSE OPTIONS UIF"));
        p.Item(H("PAUSE TAKE BUS UIF"));
        p.Item(0x534EEBC0);
        p.Item(H("PAUSE MGR UIF"));
        p.Item(H("ARROW UP UI"));
        p.Item(H("ARROW DOWN UI"));
        p.Item(H("LEVEL OFF UI 01"));
        p.Item(H("LEVEL OFF UI 02"));
        p.Item(H("LEVEL OFF UI 03"));
        p.Item(H("LEVEL OFF UI 04"));
        p.Item(H("LEVEL OFF UI 05"));
        p.Item(H("LEVEL OFF UI 06"));
        p.Item(H("LEVEL OFF UI 07"));
        p.Item(H("LEVEL OFF UI 08"));
        p.Item(H("LEVEL OFF UI 09"));
        p.Item(H("LEVEL OFF UI 10"));
        p.Item(H("LEVEL OFF UI 11"));
        p.Item(H("LEVEL OFF UI 12"));
        p.Item(H("LEVEL OFF UI 13"));
        p.Item(H("LEVEL OFF UI 14"));
        p.Item(H("LEVEL OFF UI 15"));
        p.Item(H("UI_LEVEL_PATSOCK"));
        p.Item(H("UIF_LEVEL_PATSOCK"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("PAUSE BKG GROUP"), a);
        p.Item(H("BLUE ALPHA 2 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("PAUSE OPTIONS GROUP"), a);
        p.Item(H("PAUSE OPTION MGR UIF"));
        p.Item(H("PAUSE OPTION QUIT UIF"));
        p.Item(H("PAUSE OPTION CONTROLS UIF"));
        p.Item(H(ISETTINGS_PAUSE_ENTRY));
        p.Item(H("PAUSE OPTION SAVE UIF"));
        p.Item(H("PAUSE OPTIONS PRESSX UIF"));
        p.Item(H("PAUSE OPTIONS PRESS TRI UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LEVEL BUBBLE GROUP"), a);
        p.Item(H("LEVEL ON UI 13"));
        p.Item(H("LEVEL ON UI 12"));
        p.Item(H("LEVEL ON UI 11"));
        p.Item(H("LEVEL ON UI 10"));
        p.Item(H("LEVEL ON UI 09"));
        p.Item(H("LEVEL ON UI 08"));
        p.Item(H("LEVEL ON UI 07"));
        p.Item(H("LEVEL ON UI 06"));
        p.Item(H("LEVEL ON UI 05"));
        p.Item(H("LEVEL ON UI 04"));
        p.Item(H("LEVEL ON UI 03"));
        p.Item(H("LEVEL ON UI 02"));
        p.Item(H("LEVEL ON UI 01"));
        p.Item(H("LEVEL ON UI 15"));
        p.Item(H("LEVEL ON UI 14"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("TASK GLOW UI GROUP"), a);
        p.Item(H("TASK GLOW UI 08"));
        p.Item(H("TASK GLOW UI 07"));
        p.Item(H("TASK GLOW UI 06"));
        p.Item(H("TASK GLOW UI 05"));
        p.Item(H("TASK GLOW UI 04"));
        p.Item(H("TASK GLOW UI 03"));
        p.Item(H("TASK GLOW UI 02"));
        p.Item(H("TASK GLOW UI 01"));
        p.Item(H("TASK GLOW UI BOSS 01"));
        p.Item(H("TASK GLOW UI BOSS 02"));
        p.Item(H("TASK GLOW UI BOSS 03"));
        p.Item(H("TASK GLOW UI SMALLBOSS 01"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("TASK UIF GROUP"), a);
        p.Item(H("PAUSE TASK UIF 08"));
        p.Item(H("PAUSE TASK UIF 07"));
        p.Item(H("PAUSE TASK UIF 06"));
        p.Item(H("PAUSE TASK UIF 05"));
        p.Item(H("PAUSE TASK UIF 04"));
        p.Item(H("PAUSE TASK UIF 03"));
        p.Item(H("PAUSE TASK UIF 02"));
        p.Item(H("PAUSE TASK UIF 01"));
        p.Item(H("PAUSE TASK UIF 0101"));
        p.Item(H("PAUSE TASK UIF 0301"));
        p.Item(H("PAUSE TASK UIF 0401"));
        p.Item(H("PAUSE TASK UIF 0501"));
        p.Item(H("PAUSE TASK UIF 0601"));
        p.Item(H("PAUSE TASK UIF 0701"));
        p.Item(H("PAUSE TASK UIF 0801"));
        p.Item(H("PAUSE TASK UIF 0201"));
        p.Item(H("PAUSE TASK UIF 0901"));
        p.Item(H("PAUSE TASK UIF 1101"));
        p.Item(H("PAUSE TASK UIF 1001"));
        p.Item(H("PAUSE TASK UIF 1201"));
        p.Item(H("PAUSE TASK UIF 1301"));
        p.Item(H("PAUSE TASK UIF 0102"));
        p.Item(H("PAUSE TASK UIF 0103"));
        p.Item(H("PAUSE TASK UIF 0104"));
        p.Item(H("PAUSE TASK UIF 0105"));
        p.Item(H("PAUSE TASK UIF 0106"));
        p.Item(H("PAUSE TASK UIF 0107"));
        p.Item(H("PAUSE TASK UIF 0108"));
        p.Item(H("PAUSE TASK UIF 0202"));
        p.Item(H("PAUSE TASK UIF 0203"));
        p.Item(H("PAUSE TASK UIF 0204"));
        p.Item(H("PAUSE TASK UIF 0205"));
        p.Item(H("PAUSE TASK UIF 0206"));
        p.Item(H("PAUSE TASK UIF 0207"));
        p.Item(H("PAUSE TASK UIF 0208"));
        p.Item(H("PAUSE TASK UIF 0302"));
        p.Item(H("PAUSE TASK UIF 0303"));
        p.Item(H("PAUSE TASK UIF 0304"));
        p.Item(H("PAUSE TASK UIF 0305"));
        p.Item(H("PAUSE TASK UIF 0306"));
        p.Item(H("PAUSE TASK UIF 0307"));
        p.Item(H("PAUSE TASK UIF 0308"));
        p.Item(H("PAUSE TASK UIF 0402"));
        p.Item(H("PAUSE TASK UIF 0403"));
        p.Item(H("PAUSE TASK UIF 0404"));
        p.Item(H("PAUSE TASK UIF 0405"));
        p.Item(H("PAUSE TASK UIF 0406"));
        p.Item(H("PAUSE TASK UIF 0407"));
        p.Item(H("PAUSE TASK UIF 0408"));
        p.Item(H("PAUSE TASK UIF 0602"));
        p.Item(H("PAUSE TASK UIF 0603"));
        p.Item(H("PAUSE TASK UIF 0604"));
        p.Item(H("PAUSE TASK UIF 0605"));
        p.Item(H("PAUSE TASK UIF 0606"));
        p.Item(H("PAUSE TASK UIF 0607"));
        p.Item(H("PAUSE TASK UIF 0608"));
        p.Item(H("PAUSE TASK UIF 0702"));
        p.Item(H("PAUSE TASK UIF 0703"));
        p.Item(H("PAUSE TASK UIF 0704"));
        p.Item(H("PAUSE TASK UIF 0705"));
        p.Item(H("PAUSE TASK UIF 0706"));
        p.Item(H("PAUSE TASK UIF 0707"));
        p.Item(H("PAUSE TASK UIF 0708"));
        p.Item(H("PAUSE TASK UIF 1202"));
        p.Item(H("PAUSE TASK UIF 1203"));
        p.Item(H("PAUSE TASK UIF 1204"));
        p.Item(H("PAUSE TASK UIF 1205"));
        p.Item(H("PAUSE TASK UIF 1206"));
        p.Item(H("PAUSE TASK UIF 1207"));
        p.Item(H("PAUSE TASK UIF 1208"));
        p.Item(H("PAUSE TASK UIF 1102"));
        p.Item(H("PAUSE TASK UIF 1103"));
        p.Item(H("PAUSE TASK UIF 1104"));
        p.Item(H("PAUSE TASK UIF 1105"));
        p.Item(H("PAUSE TASK UIF 1106"));
        p.Item(H("PAUSE TASK UIF 1107"));
        p.Item(H("PAUSE TASK UIF 1108"));
        p.Item(H("PAUSE TASK UIF 1002"));
        p.Item(H("PAUSE TASK UIF 1003"));
        p.Item(H("PAUSE TASK UIF 1004"));
        p.Item(H("PAUSE TASK UIF 1005"));
        p.Item(H("PAUSE TASK UIF 1006"));
        p.Item(H("PAUSE TASK UIF 1007"));
        p.Item(H("PAUSE TASK UIF 1008"));
        p.Item(H("PAUSE TASK UIF 0802"));
        p.Item(H("PAUSE TASK UIF 0803"));
        p.Item(H("PAUSE TASK UIF 0804"));
        p.Item(H("PAUSE TASK UIF 0805"));
        p.Item(H("PAUSE TASK UIF 0806"));
        p.Item(H("PAUSE TASK UIF 0807"));
        p.Item(H("PAUSE TASK UIF 0808"));
        p.Item(H("PAUSE TASK UIF 1302"));
        p.Item(H("PAUSE TASK UIF 1303"));
        p.Item(H("PAUSE TASK NONE UIF"));
        p.Item(H("PAUSE TASK UIF 1501"));
        p.Item(H("PAUSE TASK UIF 1502"));
        p.Item(H("PAUSE TASK UIF 1503"));
        p.Item(H("PAUSE TASK UIF 1504"));
        p.Item(H("PAUSE TASK UIF 1505"));
        p.Item(H("PAUSE TASK UIF 1506"));
        p.Item(H("PAUSE TASK UIF 1507"));
        p.Item(H("PAUSE TASK UIF 1508"));
        p.Item(H("PAUSE TASK UIF 1401"));
        p.Item(H("PAUSE TASK UIF 1402"));
        p.Item(H("PAUSE TASK UIF 1403"));
        p.Item(H("PAUSE TASK UIF 1404"));
        p.Item(H("PAUSE TASK UIF 1405"));
        p.Item(H("PAUSE TASK UIF 1406"));
        p.Item(H("PAUSE TASK UIF 1407"));
        p.Item(H("PAUSE TASK UIF 1408"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("PAUSE OPTIONS BKG GROUP"), a);
        p.Item(H("BLUE ALPHA 1 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("PAUSE CONTROLS GROUPS"), a);
        p.Item(H("PAUSE CONTROLS NTSC MGR UIF"));
        p.Item(H("PAUSE CONTROLS D-PAD UIF"));
        p.Item(H("PAUSE CONTROLS PRESS TRI UIF"));
        p.Item(H("BLUE ALPHA 3 UI"));
        p.Item(H("CONTROL SFX UIF"));
        p.Item(H("CONTROL MUSIC UIF"));
        p.Item(H("CONTROL VIBRATION UIF"));
        p.Item(H("CONTROL SOUND UIF"));
        p.Item(H("PAUSE CONTROLS PRESS X 2 UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MUSIC COND GROUP"), a);
        p.Item(H("MUSIC VOL COND 0"));
        p.Item(H("MUSIC VOL COND 1"));
        p.Item(H("MUSIC VOL COND 2"));
        p.Item(H("MUSIC VOL COND 3"));
        p.Item(H("MUSIC VOL COND 4"));
        p.Item(H("MUSIC VOL COND 5"));
        p.Item(H("MUSIC VOL COND 6"));
        p.Item(H("MUSIC VOL COND 7"));
        p.Item(H("MUSIC VOL COND 8"));
        p.Item(H("MUSIC VOL COND 9"));
        p.Item(H("MUSIC VOL COND 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("SFX COND GROUP"), a);
        p.Item(H("SFX VOL COND 0"));
        p.Item(H("SFX VOL COND 1"));
        p.Item(H("SFX VOL COND 2"));
        p.Item(H("SFX VOL COND 3"));
        p.Item(H("SFX VOL COND 4"));
        p.Item(H("SFX VOL COND 5"));
        p.Item(H("SFX VOL COND 6"));
        p.Item(H("SFX VOL COND 7"));
        p.Item(H("SFX VOL COND 8"));
        p.Item(H("SFX VOL COND 9"));
        p.Item(H("SFX VOL COND 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MIN MAX GROUP"), a);
        p.Item(H("CONTROL MIN UIF"));
        p.Item(H("CONTROL MAX UIF"));
        p.Item(H("HOUSE_SQUIDWARD_UI"));
        p.Item(H("HOUSE_SPONGEBOB_UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("ON OFF GROUP"), a);
        p.Item(H("CONTROL ON UIF"));
        p.Item(H("CONTROL OFF UIF"));
        p.Item(H("CONTROL OFF UI"));
        p.Item(H("CONTROL ON UI"));
        p.Item(H("HOUSE_SQUIDWARD_UI"));
        p.Item(H("HOUSE_SPONGEBOB_UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("CONTROL HASH ALL GROUP"), a);
        p.Item(H("CONTROL HASH B UI 0"));
        p.Item(H("CONTROL HASH B UI 1"));
        p.Item(H("CONTROL HASH B UI 2"));
        p.Item(H("CONTROL HASH B UI 3"));
        p.Item(H("CONTROL HASH B UI 4"));
        p.Item(H("CONTROL HASH B UI 5"));
        p.Item(H("CONTROL HASH B UI 6"));
        p.Item(H("CONTROL HASH B UI 7"));
        p.Item(H("CONTROL HASH B UI 8"));
        p.Item(H("CONTROL HASH B UI 9"));
        p.Item(H("CONTROL HASH B UI 10"));
        p.Item(H("CONTROL HASH BASE GROUP"));
        p.Item(H("KABLAM ON UI"));
        p.Item(H("KABLAM OFF UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("CONTROL HASH BASE GROUP"), a);
        p.Item(H("CONTROL HASH UI 0"));
        p.Item(H("CONTROL HASH UI 1"));
        p.Item(H("CONTROL HASH UI 2"));
        p.Item(H("CONTROL HASH UI 3"));
        p.Item(H("CONTROL HASH UI 4"));
        p.Item(H("CONTROL HASH UI 5"));
        p.Item(H("CONTROL HASH UI 6"));
        p.Item(H("CONTROL HASH UI 7"));
        p.Item(H("CONTROL HASH UI 8"));
        p.Item(H("CONTROL HASH UI 9"));
        p.Item(H("CONTROL HASH UI 10"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("SOUND MODE COND GROUP"), a);
        p.Item(H("SOUND MODE COND"));
        p.Item(H("SOUND MODE TOGGLE COND"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("VIBRATION MODE COND GROUP"), a);
        p.Item(H("VIBRATION MODE COND"));
        p.Item(H("VIBRATION MODE TOGGLE COND"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("KABLAM ALL GROUP"), a);
        p.Item(H("KABLAM OFF UI"));
        p.Item(H("KABLAM ON UI"));
        p.Item(H("CONTROL SB ON UI"));
        p.Item(H("CONTROL SB OFF UI"));
        p.Item(H("ON OFF GROUP"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("KABLAM ON GROUP"), a);
        p.Item(H("KABLAM ON UI"));
        p.Item(H("CONTROL SB ON UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("KABLAM OFF GROUP"), a);
        p.Item(H("KABLAM OFF UI"));
        p.Item(H("CONTROL SB OFF UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LD MEMCARDS GROUP"), a);
        p.Item(H("MNU3 LD MC1"));
        p.Item(H("MNU3 LD MC2"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LD FORMAT PROMPT GROUP"), a);
        p.Item(H("LD FORMAT NO"));
        p.Item(H("LD FORMAT YES"));
        p.Item(H("LD FORMAT PROMPT"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LD MC MISSING GROUP"), a);
        p.Item(H("LD MC MISSING"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("LD MEMCARDS TITLES GROUP"), a);
        p.Item(H("MNU3 LD MC2"));
        p.Item(H("MNU3 LD MC1"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU4 SCREEN ADJUST GROUP"), a);
        p.Item(H("MNU4 SCREEN MGR UIF"));
        p.Item(H("MNU4 SCREEN INF UIF"));
        p.Item(H("MNU4 SCREEN CANCEL UIF"));
        p.Item(H("MNU4 SCREEN RESET UIF"));
        p.Item(H("MNU4 SCREEN ACCEPT UIF"));
        p.Item(H("BLUE ALPHA 2 UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MNU4 PAUSE EXIT GAME GROUP"), a);
        p.Item(H("MNU4 EXIT GAME NO UIF"));
        p.Item(H("MNU4 EXIT GAME YES UIF"));
        p.Item(H("MNU4 EXIT GAME PROMPT UIF"));
        p.Item(H("BLUE ALPHA 1 UI"));
        p.Item(H("PAUSE OPTIONS PRESS TRI UIF"));
        p.Item(H("PAUSE OPTIONS PRESSX UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("SV GAMESLOT GROUP"), a);
        for (S32 i = 0; i < ISAVESCREEN_ROWS; i++)
        {
            char name[32];
            sprintf(name, ISAVESCREEN_SAVE_ROW, (int)i);
            p.Item(H(name));
        }
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("SV MEMCARDS GROUP"), a);
        p.Item(H("SV MC1"));
        p.Item(H("SV MC2"));
        p.Item(H("SV SAVE GAME TITLE UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("SV FORMAT GROUP"), a);
        p.Item(H("SV FORMAT PROMPT"));
        p.Item(H("SV FORMAT PROMPT YES"));
        p.Item(H("SV FORMAT PROMPT NO"));
        p.Link(eEventUIFocusOn, eEventUIFocusOn_Select, H("SV FORMAT PROMPT NO"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("SV MEMCARDS TITLES GROUP"), a);
        p.Item(H("SV MC1"));
        p.Item(H("SV MC2"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        p.Begin('GRUP', H("MONO STEREO GROUP"), a);
        p.Item(H("CONTROL OFF UI"));
        p.Item(H("CONTROL ON UI"));
        p.Item(H("CONTROL MONO UIF"));
        p.Item(H("CONTROL STEREO UIF"));
        p.Item(H("HOUSE_SQUIDWARD_UI"));
        p.Item(H("HOUSE_SPONGEBOB_UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("HUD TOGGLE GROUP"), a);
        p.Item(H("HUD_INT_METER_SHINY"));
        p.Item(H("HUD_INT_METER_SPATULA"));
        p.Item(H("HUD_INT_METER_SPECIAL"));
        p.Item(H("HUD_INT_METER_PATSSOCK"));
        p.Item(H("HUD_UNIT_METER_HEALTH"));
        p.Item(H("HUD_MODEL_SHINY"));
        p.Item(H("HUD_MODEL_SPATULA"));
        p.Item(H("HUD_MODEL_PATSSOCK"));
        p.Item(H("HUD_MODEL_SPECIAL"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TASK SPATULA ALL GROUP"), a);
        p.Item(H("TASK NONE UI 01"));
        p.Item(H("TASK NONE UI 02"));
        p.Item(H("TASK NONE UI 03"));
        p.Item(H("TASK NONE UI 04"));
        p.Item(H("TASK NONE UI 05"));
        p.Item(H("TASK NONE UI 06"));
        p.Item(H("TASK NONE UI 07"));
        p.Item(H("TASK NONE UI 08"));
        p.Item(H("TASK GOLDEN UI 01"));
        p.Item(H("TASK GOLDEN UI 02"));
        p.Item(H("TASK GOLDEN UI 03"));
        p.Item(H("TASK GOLDEN UI 04"));
        p.Item(H("TASK GOLDEN UI 05"));
        p.Item(H("TASK GOLDEN UI 06"));
        p.Item(H("TASK GOLDEN UI 07"));
        p.Item(H("TASK GOLDEN UI 08"));
        p.Item(H("TASK UI 01"));
        p.Item(H("TASK UI 02"));
        p.Item(H("TASK UI 03"));
        p.Item(H("TASK UI 04"));
        p.Item(H("TASK UI 05"));
        p.Item(H("TASK UI 06"));
        p.Item(H("TASK UI 07"));
        p.Item(H("TASK UI 08"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TASK SPATULA 3 GROUP"), a);
        p.Item(H("TASK NONE UI 01"));
        p.Item(H("TASK NONE UI 02"));
        p.Item(H("TASK NONE UI 03"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TASK SPATULA 1 GROUP"), a);
        p.Item(H("TASK NONE UI 01"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("SV MAKE INVISIBLE"), a);
        p.Item(H("MNU4 DISK FREE"));
        p.Item(H("MNU4 THUMBICON"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("HUD MODELS GROUP"), a);
        p.Item(H("HUD_INT_METER_SHINY"));
        p.Item(H("HUD_INT_METER_SPATULA"));
        p.Item(H("HUD_INT_METER_SPECIAL"));
        p.Item(H("HUD_INT_METER_PATSSOCK"));
        p.Item(H("HUD_UNIT_METER_HEALTH"));
        p.Item(H("HUD_MODEL_SHINY"));
        p.Item(H("HUD_MODEL_SPATULA"));
        p.Item(H("HUD_MODEL_SPECIAL"));
        p.Item(H("HUD_MODEL_PATSSOCK"));
        p.Item(H("HUD_MODEL_JF_ANTITODE"));
        p.Item(H("HUD_MODEL_BB_STEERINGWHEEL"));
        p.Item(H("HUD_MODEL_GL_BALLOON"));
        p.Item(H("HUD_MODEL_RB_ARTPIECES"));
        p.Item(H("HUD_MODEL_BC_SECURITYBUTTONS"));
        p.Item(H("HUD_MODEL_KF_LIGHTCRYSTALS"));
        p.Item(H("HUD_MODEL_GY_CANNONS"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("CAUSTICS MNU4 TEXTURE GROUP"), a);
        p.Item(H("caustics_01_001"));
        p.Item(H("caustics_01_002"));
        p.Item(H("caustics_01_003"));
        p.Item(H("caustics_01_004"));
        p.Item(H("caustics_01_005"));
        p.Item(H("caustics_01_006"));
        p.Item(H("caustics_01_007"));
        p.Item(H("caustics_01_008"));
        p.Item(H("caustics_01_009"));
        p.Item(H("caustics_01_010"));
        p.Item(H("caustics_01_011"));
        p.Item(H("caustics_01_012"));
        p.Item(H("caustics_01_013"));
        p.Item(H("caustics_01_014"));
        p.Item(H("caustics_01_015"));
        p.Item(H("caustics_01_016"));
        p.Item(H("caustics_01_017"));
        p.Item(H("caustics_01_018"));
        p.Item(H("caustics_01_019"));
        p.Item(H("caustics_01_020"));
        p.Item(H("caustics_01_021"));
        p.Item(H("caustics_01_022"));
        p.Item(H("caustics_01_023"));
        p.Item(H("caustics_01_024"));
        p.Item(H("caustics_01_025"));
        p.Item(H("caustics_01_026"));
        p.Item(H("caustics_01_027"));
        p.Item(H("caustics_01_028"));
        p.Item(H("caustics_01_029"));
        p.Item(H("caustics_01_030"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("PAUSE CONTROLS GC/XB GROUP"), a);
        p.Item(H("MNU4 CONTROL MUSIC GC/XB UIF"));
        p.Item(H("MNU4 CONTROL SFX GC/XB UIF"));
        p.Item(H("MNU4 CONTROL VIBE GC/XB UIF"));
        p.Item(H("PAUSE CONTROLS PRESS TRI UIF"));
        p.Item(H("PAUSE CONTROLS D-PAD UIF"));
        p.Item(H("BLUE ALPHA 3 UI"));
        p.Item(H("PAUSE CONTROLS GC/XB MGR UIF"));
        p.Item(H("PAUSE CONTROLS PRESS X 2 UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1C;
        p.Begin('GRUP', H("PAUSE CONTROLS GC/XB PAL GROUP"), a);
        p.Item(0x79CACEE8);
        p.Item(H("MNU4 CONTROL SFX GC/XB PAL UIF"));
        p.Item(H("MNU4 CONTROL VIBE GC/XB PAL UIF"));
        p.Item(H("PAUSE CONTROLS PRESS TRI UIF"));
        p.Item(H("PAUSE CONTROLS D-PAD UIF"));
        p.Item(H("BLUE ALPHA 3 UI"));
        p.Item(0x6C9E696E);
        p.Item(H("PAUSE CONTROLS PRESS X 2 UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("PAUSE CONTROLS PAL GROUP"), a);
        p.Item(H("MNU4 CONTROL SCREEN PAL UIF"));
        p.Item(H("MNU4 CONTROL MUSIC PAL UIF"));
        p.Item(H("MNU4 CONTROL SFX PAL UIF"));
        p.Item(H("MNU4 CONTROL SOUND PAL UIF"));
        p.Item(H("MNU4 CONTROL VIBE PAL UIF"));
        p.Item(H("BLUE ALPHA 3 UI"));
        p.Item(H("PAUSE CONTROLS PRESS TRI UIF"));
        p.Item(H("PAUSE CONTROLS D-PAD UIF"));
        p.Item(H("PAUSE CONTROLS PAL MGR UIF"));
        p.Item(H("PAUSE CONTROLS PRESS X 2 UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("GAME PAUSED GROUP"), a);
        p.Item(H("PAUSE GAME PAUSED UIF"));
        p.Item(H("PAUSE GAME PAUSED UIF 2"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("ARROW UP DOWN OBJ GROUP"), a);
        p.Item(H("ARROW UP UI"));
        p.Item(H("ARROW DOWN UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TAXI CONFIRM GROUP"), a);
        p.Item(H("TAXI PROMPT NO"));
        p.Item(H("TAXI CONFIRM UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("LEVEL UIF GROUP"), a);
        p.Item(H("PAUSE LEVEL UIF1"));
        p.Item(H("PAUSE LEVEL UIF2"));
        p.Item(H("PAUSE LEVEL UIF3"));
        p.Item(H("PAUSE LEVEL UIF4"));
        p.Item(H("PAUSE LEVEL UIF5"));
        p.Item(H("PAUSE LEVEL UIF6"));
        p.Item(H("PAUSE LEVEL UIF7"));
        p.Item(H("PAUSE LEVEL UIF8"));
        p.Item(H("PAUSE LEVEL UIF9"));
        p.Item(H("PAUSE LEVEL UIF10"));
        p.Item(H("PAUSE LEVEL UIF11"));
        p.Item(H("PAUSE LEVEL UIF12"));
        p.Item(H("PAUSE LEVEL UIF13"));
        p.Item(H("PAUSE LEVEL UIF14"));
        p.Item(H("PAUSE LEVEL UIF15"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TAXI CONFIRM HIDE MENU GROUP"), a);
        p.Item(H("PAUSE OPTIONS UIF"));
        p.Item(H("PAUSE RETURN GAME UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("UI HIDE LEFTOVERS GROUP"), a);
        p.Item(H("AAA MNU4 CAUSTICS SURFACE UI"));
        p.Item(H("TAXI CONFIRM KABLAM UI"));
        p.Item(H("SAVING GAME ICON UI"));
        p.Item(H("PAUSE GAME PAUSED KABLAM UI"));
        p.Item(H("TAXI CONFIRM MGR UIF"));
        p.Item(H("TAXI PROMPT NO"));
        p.Item(H("TAXI CONFIRM UIF"));
        p.Item(H("LEVEL UIF GROUP"));
        p.Item(H("TASK UIF GROUP"));
        p.Item(H("LEVEL BUBBLE GROUP"));
        p.Item(H("TASK GLOW UI GROUP"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("ARROW UP DOWN GLOW OBJ GROUP"), a);
        p.Item(H("ARROW UP GLOW UI"));
        p.Item(H("ARROW DOWN GLOW UI"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("GAME PAUSED TIMER GROUP"), a);
        p.Item(H("PAUSE_TIMER46"));
        p.Item(H("PAUSE_TIMER47"));
        p.Link(eEventStop, eEventInvisible, H("GAME PAUSED GROUP"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TAXI CONFIRM TIMER GROUP"), a);
        p.Item(H("PAUSE_TIMER50"));
        p.Item(H("PAUSE_TIMER51"));
        p.Link(eEventStop, eEventInvisible, H("TAXI CONFIRM FLASHING GROUP"));
        p.Link(eEventStop, eEventUIFocusOff_Unselect, H("TAXI CONFIRM MGR UIF"));
        p.End();
    }

    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H("TAXI CONFIRM FLASHING GROUP"), a);
        p.Item(H("TAXI CONFIRM UIF 2"));
        p.Item(H("TAXI CONFIRM UIF 1"));
        p.End();
    }
}

static zCondAsset CondDefaultsInit()
{
    zCondAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeCond;
    a.baseFlags = 0xD;
    a.constNum = 1;
    a.expr1 = H("Music Volume");
    return a;
}

static const zCondAsset kCondDefaults = CondDefaultsInit();

void MNU4_BuildCond(iAssetPkg& p)
{
    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Sound mode");
        p.Begin('COND', H("SOUND MODE COND"), a);
        p.Link(eEventFalse, eEventVisible, H("KABLAM OFF GROUP"));
        p.Link(eEventFalse, eEventInvisible, H("KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventVisible, H("KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventInvisible, H("KABLAM OFF GROUP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Sound mode");
        p.Begin('COND', H("SOUND MODE TOGGLE COND"), a);
        p.Link(eEventTrue, eEventDispatcher_SoundMono, H("MNU4 CONTROLS DISP"));
        p.Link(eEventFalse, eEventDispatcher_SoundStereo, H("MNU4 CONTROLS DISP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Vibration is on");
        p.Begin('COND', H("VIBRATION MODE COND"), a);
        p.Link(eEventFalse, eEventVisible, H("KABLAM OFF GROUP"));
        p.Link(eEventFalse, eEventInvisible, H("KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventVisible, H("KABLAM ON GROUP"));
        p.Link(eEventTrue, eEventInvisible, H("KABLAM OFF GROUP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("Vibration is on");
        p.Begin('COND', H("VIBRATION MODE TOGGLE COND"), a);
        p.Link(eEventTrue, eEventDispatcher_PadVibrateOff, H("MNU4 CONTROLS DISP"));
        p.Link(eEventFalse, eEventDispatcher_PadVibrateOn, H("MNU4 CONTROLS DISP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 0;
        p.Begin('COND', H("MUSIC VOL COND 0"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 0"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 0"));
        p.Link(eEventTrue, eEventPlay, H("MNU4 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        p.Begin('COND', H("MUSIC VOL COND 1"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 1"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 1"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 2;
        p.Begin('COND', H("MUSIC VOL COND 2"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 2"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 2"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 3;
        p.Begin('COND', H("MUSIC VOL COND 3"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 3"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 3"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 4;
        p.Begin('COND', H("MUSIC VOL COND 4"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 4"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 4"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 5;
        p.Begin('COND', H("MUSIC VOL COND 5"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 5"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 5"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 6;
        p.Begin('COND', H("MUSIC VOL COND 6"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 6"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 6"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 7;
        p.Begin('COND', H("MUSIC VOL COND 7"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 7"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 7"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 8;
        p.Begin('COND', H("MUSIC VOL COND 8"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 8"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 8"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 9;
        p.Begin('COND', H("MUSIC VOL COND 9"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 9"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 9"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 10;
        p.Begin('COND', H("MUSIC VOL COND 10"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 10"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 10"));
        p.Link(eEventTrue, eEventPlay, H("MNU4 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 0;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 0"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 0"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 0"));
        p.Link(eEventTrue, eEventPlay, H("MNU4 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 1"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 1"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 1"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 2;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 2"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 2"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 2"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 3;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 3"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 3"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 3"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 4;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 4"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 4"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 4"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 5;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 5"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 5"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 5"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 6;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 6"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 6"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 6"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 7;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 7"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 7"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 7"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 8;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 8"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 8"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 8"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 9;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 9"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 9"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 9"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.constNum = 10;
        a.expr1 = H("SFX Volume");
        p.Begin('COND', H("SFX VOL COND 10"), a);
        p.Link(eEventTrue, eEventVisible, H("CONTROL HASH B UI 10"));
        p.Link(eEventFalse, eEventInvisible, H("CONTROL HASH B UI 10"));
        p.Link(eEventTrue, eEventPlay, H("MNU4 PING SFX"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.baseFlags = 0x1D;
        a.constNum = 0;
        a.expr1 = H("Shiny Objects");
        p.Begin('COND', H("TASK COND HB01"), a);
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.baseFlags = 0x1D;
        a.expr1 = H("Is Visible (0=No, 1=Yes)");
        a.value_asset = H("PAUSE TAKE BUS UIF");
        p.Begin('COND', H("TAXI CONFIRM COND"), a);
        p.Link(eEventTrue, eEventPlay, H("MNU4 CONFIRM SFX"));
        p.Link(eEventFalse, eEventPlay, H("MNU4 DENY SFX"));
        p.Link(eEventTrue, eEventUISelect, H("TAXI PROMPT NO"));
        p.Link(eEventTrue, eEventDisable, H("PAUSE MGR UIF"));
        p.Link(eEventTrue, eEventInvisible, H("TAXI CONFIRM HIDE MENU GROUP"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.baseFlags = 0x1D;
        a.expr1 = H("Is Visible (0=No, 1=Yes)");
        a.value_asset = H("BLUE ALPHA 2 UI");
        p.Begin('COND', H("ARROW VISIBLE COND UP"), a);
        p.Link(eEventTrue, eEventVisible, H("ARROW UP UI"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.baseFlags = 0x1D;
        a.expr1 = H("Is Visible (0=No, 1=Yes)");
        a.value_asset = H("BLUE ALPHA 2 UI");
        p.Begin('COND', H("ARROW VISIBLE COND DN"), a);
        p.Link(eEventTrue, eEventVisible, H("ARROW DOWN UI"));
        p.End();
    }

    {
        zCondAsset a = kCondDefaults;
        a.baseFlags = 0x1D;
        a.expr1 = H("Is Visible (0=No, 1=Yes)");
        a.value_asset = H("TAXI PROMPT NO");
        p.Begin('COND', H("VERIFY TAXI VISIBLE COND"), a);
        p.Link(eEventTrue, eEventInvisible, H("TAXI BUG 6196 FIX UIF"));
        p.End();
    }
}

static xTimerAsset TimerDefaultsInit()
{
    xTimerAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeTimer;
    a.baseFlags = 0x1D;
    a.seconds = 0.1f;
    return a;
}

static const xTimerAsset kTimerDefaults = TimerDefaultsInit();

void MNU4_BuildTimer(iAssetPkg& p)
{
    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER0"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER0"));
        p.Link(eEventRun, eEventVisible, H("ARROW UP GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("ARROW UP GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER1"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER1"));
        p.Link(eEventRun, eEventVisible, H("ARROW DOWN GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("ARROW DOWN GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER2"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER2"));
        p.Link(eEventRun, eEventVisible, H("CONTROL OFF GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("CONTROL OFF GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        p.Begin('TIMR', H("PAUSE_TIMER3"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER3"));
        p.Link(eEventRun, eEventVisible, H("CONTROL ON GLOW UI"));
        p.Link(eEventExpired, eEventInvisible, H("CONTROL ON GLOW UI"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.baseFlags = 0xD;
        a.seconds = 1.5f;
        p.Begin('TIMR', H("PAUSE_TIMER8"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER8"));
        p.Link(eEventExpired, eEventDispatcher_SetGameState_Exit, H("MNU4 CONTROLS DISP"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 1.0f;
        p.Begin('TIMR', H("HUD TOGGLE TIMER"), a);
        p.Link(eEventExpired, eEventReset, H("HUD TOGGLE TIMER"));
        p.Link(eEventRun, eEventDispatcher_ShowHud, H("HUD TOGGLE GROUP"));
        p.Link(eEventExpired, eEventDispatcher_HideHud, H("HUD TOGGLE GROUP"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 2.0f;
        p.Begin('TIMR', H("SAVE_COMPLETED_TIMER"), a);
        p.Link(eEventExpired, eEventReset, H("SAVE_COMPLETED_TIMER"));
        p.Link(eEventExpired, eEventInvisible, H("MNU4 SAVE COMPLETED"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 10.0f;
        p.Begin('TIMR', H("AUTO_SAVE_FAILED_TIMER"), a);
        p.Link(eEventExpired, eEventReset, H("AUTO_SAVE_FAILED_TIMER"));
        p.Link(eEventExpired, eEventInvisible, H("MNU4 AUTO SAVE FAILED"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        p.Begin('TIMR', H("PAUSE_TIMER44"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER44"));
        p.Link(eEventExpired, eEventRun, H("PAUSE_TIMER45"));
        p.Link(eEventRun, eEventEnable, H("GAME PAUSED TIMER GROUP"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 3.0f;
        p.Begin('TIMR', H("PAUSE_TIMER45"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER45"));
        p.Link(eEventRun, eEventRun, H("PAUSE_TIMER46"));
        p.Link(eEventExpired, eEventStop, H("GAME PAUSED TIMER GROUP"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.04f;
        p.Begin('TIMR', H("PAUSE_TIMER21"), a);
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.01f;
        p.Begin('TIMR', H("PAUSE_TIMER22"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER22"));
        p.Link(eEventExpired, eEventUIFocusOff_Unselect, H("TAXI CONFIRM GROUP"));
        p.Link(eEventExpired, eEventUIFocusOn, H("PAUSE GROUP"));
        p.Link(eEventExpired, eEventVisible, H("TAXI CONFIRM HIDE MENU GROUP"));
        p.Link(eEventExpired, eEventEnable, H("PAUSE MGR UIF"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.6f;
        p.Begin('TIMR', H("PAUSE_TIMER86"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER86"));
        p.Link(eEventExpired, eEventDispatcher_SetGameState_Exit, H("PAUSE STATE DISP"));
        p.Link(eEventExpired, eEventDispatcher_FadeOut, H("PAUSE STATE DISP"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.2f;
        p.Begin('TIMR', H("PAUSE_TIMER46"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER46"));
        p.Link(eEventExpired, eEventRun, H("PAUSE_TIMER47"));
        p.Link(eEventRun, eEventVisible, H("PAUSE GAME PAUSED UIF"));
        p.Link(eEventExpired, eEventInvisible, H("PAUSE GAME PAUSED UIF"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.2f;
        p.Begin('TIMR', H("PAUSE_TIMER47"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER47"));
        p.Link(eEventExpired, eEventRun, H("PAUSE_TIMER46"));
        p.Link(eEventRun, eEventVisible, H("PAUSE GAME PAUSED UIF 2"));
        p.Link(eEventExpired, eEventInvisible, H("PAUSE GAME PAUSED UIF 2"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.2f;
        p.Begin('TIMR', H("PAUSE_TIMER50"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER50"));
        p.Link(eEventExpired, eEventRun, H("PAUSE_TIMER51"));
        p.Link(eEventRun, eEventVisible, H("TAXI CONFIRM UIF 1"));
        p.Link(eEventExpired, eEventInvisible, H("TAXI CONFIRM UIF 1"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.2f;
        p.Begin('TIMR', H("PAUSE_TIMER51"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER51"));
        p.Link(eEventExpired, eEventRun, H("PAUSE_TIMER50"));
        p.Link(eEventRun, eEventVisible, H("TAXI CONFIRM UIF 2"));
        p.Link(eEventExpired, eEventInvisible, H("TAXI CONFIRM UIF 2"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.01f;
        p.Begin('TIMR', H("PAUSE_TIMER33"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER33"));
        p.Link(eEventExpired, eEventEvaluate, H("TAXI CONFIRM COND"));
        p.End();
    }

    {
        xTimerAsset a = kTimerDefaults;
        a.seconds = 0.05f;
        p.Begin('TIMR', H("PAUSE_TIMER99"), a);
        p.Link(eEventExpired, eEventReset, H("PAUSE_TIMER99"));
        p.Link(eEventExpired, eEventEvaluate, H("VERIFY TAXI VISIBLE COND"));
        p.Link(eEventExpired, eEventStop, H("TAXI CONFIRM TIMER GROUP"));
        p.End();
    }
}

static xBaseAsset DispatcherDefaultsInit()
{
    xBaseAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeDispatcher;
    a.baseFlags = 0xD;
    return a;
}

static const xBaseAsset kDispatcherDefaults = DispatcherDefaultsInit();

void MNU4_BuildDispatcher(iAssetPkg& p)
{
    {
        xBaseAsset a = kDispatcherDefaults;
        p.Begin('DPAT', H("PAUSE STATE DISP"), a);
        p.Link(eEventDispatcher_PauseState_Pause, eEventUIFocusOn, H("PAUSE GROUP"));
        p.Link(eEventDispatcher_PauseState_Pause, eEventUISelect, H("PAUSE MGR UIF"));
        p.Link(eEventDispatcher_GameState_Play, eEventUIFocusOff_Unselect, H("PAUSE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("PAUSE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("PAUSE BKG GROUP"));
        p.Link(eEventDispatcher_PauseState_Pause, eEventPlay, H("MNU4 AMBIENT SFX"));
        p.Link(eEventDispatcher_GameState_Play, eEventStop, H("MNU4 AMBIENT SFX"));
        p.Link(eEventDispatcher_GameState_Play, eEventUIFocusOff_Unselect, H("LEVEL BUBBLE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("LEVEL BUBBLE GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("PAUSE OPTIONS BKG GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventUIFocusOff_Unselect, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventDispatcher_PauseState_Pause, eEventRun, H("PAUSE_TIMER44"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("GAME PAUSED GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventExpired, H("GAME PAUSED GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("UI HIDE LEFTOVERS GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventInvisible, H("UI HIDE LEFTOVERS GROUP"));
        p.Link(eEventDispatcher_GameState_Play, eEventReset, H("PAUSE_TIMER45"));
        p.Link(eEventDispatcher_GameState_Play, eEventStop, H("TAXI CONFIRM TIMER GROUP"));
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        p.Begin('DPAT', H("MNU4 CONTROLS DISP"), a);
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        a.baseFlags = 0x1D;
        p.Begin('DPAT', H("SV DISPATCH"), a);
        p.End();
    }

    {
        xBaseAsset a = kDispatcherDefaults;
        a.baseFlags = 0x1D;
        p.Begin('DPAT', H("HUD TOGGLE DISP"), a);
        p.Link(eEventSceneBegin, eEventUIFocusOn_Select, H("HUD TOGGLE UIF"));
        p.End();
    }
}

static xSFXAsset SFXDefaultsInit()
{
    xSFXAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeSFX;
    a.baseFlags = 0xD;
    a.flagsSFX = 0x1C0;
    a.freqm = 1.0f;
    a.soundAssetID = H("mnu4_exit");
    a.priority = 128;
    a.volume = 91;
    a.pos = xVec3{ 64.2824f, 29.8777f, 64.2824f };
    a.innerRadius = 10.0f;
    return a;
}

static const xSFXAsset kSFXDefaults = SFXDefaultsInit();

void MNU4_BuildSFX(iAssetPkg& p)
{
    {
        xSFXAsset a = kSFXDefaults;
        a.flagsSFX = 0x1E4;
        a.soundAssetID = H("mnu4_Bub_amb_loop");
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU4 AMBIENT SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu4_SB_jog1L");
        p.Begin('SFX ', H("MNU4 MOVE A SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu4_SB_jog1R");
        p.Begin('SFX ', H("MNU4 MOVE B SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu4_bubblewand");
        p.Begin('SFX ', H("MNU4 CONFIRM SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("mnu4_Pop_in");
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU4 PING SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        p.Begin('SFX ', H("MNU4 BACK SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.pos = xVec3{ 64.2824f, 29.8778f, 64.2824f };
        p.Begin('SFX ', H("MNU4 EXIT SFX"), a);
        p.End();
    }

    {
        xSFXAsset a = kSFXDefaults;
        a.soundAssetID = H("sax");
        p.Begin('SFX ', H("MNU4 DENY SFX"), a);
        p.End();
    }
}

static xCounterAsset CounterDefaultsInit()
{
    xCounterAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeCounter;
    a.baseFlags = 0xF;
    return a;
}

static const xCounterAsset kCounterDefaults = CounterDefaultsInit();

void MNU4_BuildCounter(iAssetPkg& p)
{
    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("MNU3 MNU4 COUNTER"), a);
        p.Link(eEventRoomBegin, eEventIncrement, H("MNU3 MNU4 COUNTER"));
        p.End();
    }
}

static xPortalAsset PortalDefaultsInit()
{
    xPortalAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypePortal;
    a.baseFlags = 0xD;
    a.assetCameraID = H("STARTCAM");
    a.assetMarkerID = 0x76E17D6E;
    a.sceneID = iAssetTag("SB10");
    return a;
}

static const xPortalAsset kPortalDefaults = PortalDefaultsInit();

void MNU4_BuildPortal(iAssetPkg& p)
{
    {
        xPortalAsset a = kPortalDefaults;
        p.Begin('PORT', H("EXIT LEVEL PORTAL"), a);
        p.End();
    }

    {
        xPortalAsset a = kPortalDefaults;
        a.assetCameraID = 0xACEF4597;
        a.assetMarkerID = H("FROM MNU4");
        a.sceneID = iAssetTag("SM40");
        p.Begin('PORT', H("WARP TO SM40"), a);
        p.End();
    }

    // The settings screen's widgets, shown and focused together.
    {
        xGroupAsset a = kGroupDefaults;
        a.baseFlags = 0x1D;
        p.Begin('GRUP', H(ISETTINGS_GROUP), a);
        p.Item(H(ISETTINGS_TITLE));
        for (S32 i = 0; i < ISETTINGS_ROWS; i++)
        {
            char name[32];
            sprintf(name, ISETTINGS_LABEL, (int)i);
            p.Item(H(name));
            sprintf(name, ISETTINGS_VALUE, (int)i);
            p.Item(H(name));
        }
        p.Item(H(ISETTINGS_HELP));
        p.End();
    }
}
