// Generated by tools/menugen/menugen.py from the Xbox mnu4.HIP, then kept by
// hand. This file is the source of MNU4's asset list now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

// The types this package builds. The HIP's own assets of these types are
// never seen; everything else in it is used as shipped.
extern const U32 kMNU4OwnedTypes[] = { 'TEXT', 'UI  ', 'UIFT', 'DYNA', 'GRUP', 'COND', 'TIMR', 'DPAT', 'SFX ', 'CNTR', 'PORT', 0 };

void MNU4_BuildText(iAssetPkg& p);
void MNU4_BuildUI(iAssetPkg& p);
void MNU4_BuildUIFont(iAssetPkg& p);
void MNU4_BuildDyna(iAssetPkg& p);
void MNU4_BuildGroup(iAssetPkg& p);
void MNU4_BuildCond(iAssetPkg& p);
void MNU4_BuildTimer(iAssetPkg& p);
void MNU4_BuildDispatcher(iAssetPkg& p);
void MNU4_BuildSFX(iAssetPkg& p);
void MNU4_BuildCounter(iAssetPkg& p);
void MNU4_BuildPortal(iAssetPkg& p);

void MNU4_Build(iAssetPkg& p)
{
    MNU4_BuildText(p);
    MNU4_BuildUI(p);
    MNU4_BuildUIFont(p);
    MNU4_BuildDyna(p);
    MNU4_BuildGroup(p);
    MNU4_BuildCond(p);
    MNU4_BuildTimer(p);
    MNU4_BuildDispatcher(p);
    MNU4_BuildSFX(p);
    MNU4_BuildCounter(p);
    MNU4_BuildPortal(p);
}
