// Generated by tools/menugen/menugen.py from the Xbox mnu4.HIP, then kept by
// hand. This file is the source of MNU4's UI widgets now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static zUIAsset UIDefaultsInit()
{
    zUIAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeUI;
    a.baseFlags = 0xD;
    a.moreFlags = 0x2;
    a.pos = xVec3{ 0.0f, 0.0f, 90.0f };
    a.scale = xVec3{ 1.0f, 1.0f, 1.0f };
    a.redMult = 1.0f;
    a.greenMult = 1.0f;
    a.blueMult = 1.0f;
    a.seeThru = 1.0f;
    a.seeThruSpeed = 255.0f;
    a.uiFlags = 0x34;
    a.dim[0] = 50; a.dim[1] = 50;
    a.uvb[0] = 1.0f; a.uvb[1] = 0.0f;
    a.uvc[0] = 1.0f; a.uvc[1] = 1.0f;
    a.uvd[0] = 0.0f; a.uvd[1] = 1.0f;
    return a;
}

static const zUIAsset kUIDefaults = UIDefaultsInit();

void MNU4_BuildUI(iAssetPkg& p)
{
    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 150.0f, 1.0f };
        a.scale = xVec3{ 0.8f, 0.8f, 0.8f };
        a.modelInfoID = H("ui_3dicon_jellyfish");
        a.animListID = H("JELLYFISH IDLE ANIMLIST");
        p.Begin('UI  ', H("ARROW UP UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 60.0f, 140.0f, 0.0f };
        a.scale = xVec3{ 0.8f, 0.8f, 0.8f };
        a.modelInfoID = H("ui_3dicon_jellyfish");
        a.animListID = H("JELLYFISH IDLE ANIMLIST");
        p.Begin('UI  ', H("ARROW UP GLOW UI"), a);
        p.Link(eEventVisible, eEventInvisible, H("ARROW UP UI"));
        p.Link(eEventInvisible, eEventEvaluate, H("ARROW VISIBLE COND UP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 0.0f, 3.1415927f, 0.0f };
        a.pos = xVec3{ 60.0f, 300.0f, 0.0f };
        a.scale = xVec3{ 0.8f, 0.8f, 0.8f };
        a.modelInfoID = H("ui_3dicon_jellyfish");
        a.animListID = H("JELLYFISH IDLE ANIMLIST");
        a.uva[0] = 1.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("ARROW DOWN GLOW UI"), a);
        p.Link(eEventVisible, eEventInvisible, H("ARROW DOWN UI"));
        p.Link(eEventInvisible, eEventEvaluate, H("ARROW VISIBLE COND DN"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 0.0f, 3.1415927f, 0.0f };
        a.pos = xVec3{ 60.0f, 290.0f, 1.0f };
        a.scale = xVec3{ 0.8f, 0.8f, 0.8f };
        a.modelInfoID = H("ui_3dicon_jellyfish");
        a.animListID = H("JELLYFISH IDLE ANIMLIST");
        a.uva[0] = 1.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("ARROW DOWN UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 160.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 01"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 170.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 02"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 180.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 03"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 190.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 04"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 200.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 05"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 210.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 06"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 220.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 07"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 230.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 08"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 240.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 09"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 250.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 260.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 11"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 270.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 12"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 280.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 13"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_2");
        p.Begin('UI  ', H("BLUE ALPHA 2 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 2 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 2 BAMBOO UI"));
        p.Link(eEventVisible, eEventVisible, H("HUD MODELS GROUP"));
        p.Link(eEventVisible, eEventVisible, H("AAA MNU4 CAUSTICS SURFACE UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 160.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 01"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 01"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 02"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF1"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF1"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("TASK SPATULA ALL GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 170.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 02"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 02"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 02"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 02"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 02"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 03"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF2"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF2"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 180.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 03"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 03"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 03"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 03"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 04"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 03"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 02"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF3"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF3"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 190.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 04"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 04"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 04"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 04"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 05"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 04"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 03"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF4"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF4"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressDown, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 200.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 05"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 05"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 05"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 05"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 06"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 05"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 04"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF5"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF5"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("TASK SPATULA 1 GROUP"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 210.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 06"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 06"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 06"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 06"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 07"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 06"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 05"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF6"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF6"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressUp, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 220.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 07"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 07"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 07"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 07"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 08"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 07"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 06"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF7"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF7"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 230.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 08"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 08"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 08"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 08"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 09"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 08"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 07"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF8"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF8"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressDown, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 240.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 09"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 09"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 09"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 09"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 10"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 09"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 08"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF9"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF9"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("TASK SPATULA 1 GROUP"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 250.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 10"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 10"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 10"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 10"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 11"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 10"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 09"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF10"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF10"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI SMALLBOSS 01"));
        p.Link(eEventPadPressUp, eEventVisible, H("TASK SPATULA 1 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 260.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 11"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 11"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 11"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 11"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 12"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 11"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 10"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF11"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF11"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 270.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 12"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 12"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 12"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 12"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 13"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 12"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 11"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF12"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF12"));
        p.Link(eEventUISelect, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventPadPressDown, eEventVisible, H("TASK SPATULA 3 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 280.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 13"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 13"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 13"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 13"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 12"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF13"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF13"));
        p.Link(eEventPadPressUp, eEventInvisible, H("TASK SPATULA 3 GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressUp, eEventVisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 13"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 14"));
        p.Link(eEventPadPressDown, eEventInvisible, H("TASK SPATULA 3 GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 130.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST0");
        p.Begin('UI  ', H("TASK NONE UI 01"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 180.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST1");
        p.Begin('UI  ', H("TASK NONE UI 02"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 230.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST2");
        p.Begin('UI  ', H("TASK NONE UI 03"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 280.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST0");
        p.Begin('UI  ', H("TASK NONE UI 04"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 330.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST1");
        p.Begin('UI  ', H("TASK NONE UI 05"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 380.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST2");
        p.Begin('UI  ', H("TASK NONE UI 06"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 430.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST0");
        p.Begin('UI  ', H("TASK NONE UI 07"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 480.0f, 210.0f, 4.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 1.0f };
        a.modelInfoID = H("ui_3dicon_question");
        a.animListID = H("QUESTION ANIM LIST1");
        p.Begin('UI  ', H("TASK NONE UI 08"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 120.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 01"), a);
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 02"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 01"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 170.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 02"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 02"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 01"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 02"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 03"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 02"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 02"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 220.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 03"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 03"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 02"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 03"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 04"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 03"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 03"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 270.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 04"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 04"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 03"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 04"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 05"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 04"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 04"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 320.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 05"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 05"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 04"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 05"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 06"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 05"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 05"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 06"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 06"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 05"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 06"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 07"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 06"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 06"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 420.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 07"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 07"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 06"));
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI 07"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI 08"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 07"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 07"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI 08"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI 08"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI 07"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 08"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 08"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_1");
        p.Begin('UI  ', H("BLUE ALPHA 1 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 1 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 1 BAMBOO UI"));
        p.Link(eEventVisible, eEventInvisible, H("HUD MODELS GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_0");
        p.Begin('UI  ', H("CONTROL VALUE UI 0"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 300.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_1");
        p.Begin('UI  ', H("CONTROL VALUE UI 1"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 320.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_2");
        p.Begin('UI  ', H("CONTROL VALUE UI 2"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 340.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_3");
        p.Begin('UI  ', H("CONTROL VALUE UI 3"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 360.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_4");
        p.Begin('UI  ', H("CONTROL VALUE UI 4"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 140.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_5");
        p.Begin('UI  ', H("CONTROL VALUE UI 5"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 400.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_6");
        p.Begin('UI  ', H("CONTROL VALUE UI 6"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 420.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_7");
        p.Begin('UI  ', H("CONTROL VALUE UI 7"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 440.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_8");
        p.Begin('UI  ', H("CONTROL VALUE UI 8"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 460.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_9");
        p.Begin('UI  ', H("CONTROL VALUE UI 9"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 150.0f, 2.0f };
        a.dim[0] = 60; a.dim[1] = 60;
        a.textureID = H("ui_iconsb_10");
        p.Begin('UI  ', H("CONTROL VALUE UI 10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.dim[0] = 640; a.dim[1] = 480;
        a.textureID = H("ui_blue_alpha_3");
        p.Begin('UI  ', H("BLUE ALPHA 3 UI"), a);
        p.Link(eEventVisible, eEventVisible, H("BLUE ALPHA 3 BAMBOO UI"));
        p.Link(eEventInvisible, eEventInvisible, H("BLUE ALPHA 3 BAMBOO UI"));
        p.Link(eEventVisible, eEventInvisible, H("HUD MODELS GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 220.0f, 130.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_house_squidward");
        p.Begin('UI  ', H("HOUSE_SQUIDWARD_UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 520.0f, 130.0f, 1.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_house_spongebob");
        p.Begin('UI  ', H("HOUSE_SPONGEBOB_UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 50.0f, 2.0f };
        a.scale = xVec3{ 1.0f, 0.4f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 260; a.dim[1] = 100;
        p.Begin('UI  ', H("KABLAM_UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 50.0f, 2.0f };
        a.scale = xVec3{ -1.0f, 0.4f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 260; a.dim[1] = 100;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM 2 UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 0"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 1"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 2"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 350.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 3"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 4"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 390.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 5"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 410.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 6"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 7"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 450.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 8"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 210.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 9"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 490.0f, 200.0f, 2.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_y");
        p.Begin('UI  ', H("CONTROL HASH UI 10"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 290.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 0"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 0"));
        p.Link(eEventVisible, eEventVisible, H("KABLAM OFF SMALL UI"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 0"));
        p.Link(eEventInvisible, eEventInvisible, H("KABLAM OFF SMALL UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 1"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 1"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 1"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 2"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 2"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 2"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 350.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 3"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 3"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 3"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 4"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 4"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 4"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 390.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 5"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 5"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 5"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 410.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 6"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 6"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 6"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 7"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 7"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 7"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 450.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 8"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 8"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 8"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 210.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 40;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 9"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 9"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 9"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 490.0f, 200.0f, 1.0f };
        a.dim[0] = 40; a.dim[1] = 50;
        a.textureID = H("ui_bamboo_b");
        p.Begin('UI  ', H("CONTROL HASH B UI 10"), a);
        p.Link(eEventVisible, eEventVisible, H("CONTROL VALUE UI 10"));
        p.Link(eEventVisible, eEventVisible, H("KABLAM ON SMALL UI"));
        p.Link(eEventInvisible, eEventInvisible, H("CONTROL VALUE UI 10"));
        p.Link(eEventInvisible, eEventInvisible, H("KABLAM ON SMALL UI"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 200.0f, 3.0f };
        a.textureID = H("ui_arrowup");
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 1.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 0.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("CONTROL OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 310.0f, 200.0f, 2.0f };
        a.textureID = H("ui_arrowup_glow");
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 1.0f; a.uvb[1] = 1.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 0.0f; a.uvd[1] = 0.0f;
        p.Begin('UI  ', H("CONTROL OFF GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 200.0f, 3.0f };
        a.textureID = H("ui_arrowup");
        a.uva[0] = 0.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 1.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("CONTROL ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 470.0f, 200.0f, 2.0f };
        a.textureID = H("ui_arrowup_glow");
        a.uva[0] = 0.0f; a.uva[1] = 1.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 1.0f; a.uvc[1] = 0.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("CONTROL ON GLOW UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 225.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.5f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 523.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.5f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 190.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_iconsb_0");
        p.Begin('UI  ', H("CONTROL SB OFF UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 370.0f, 190.0f, 2.0f };
        a.dim[0] = 80; a.dim[1] = 80;
        a.textureID = H("ui_iconsb_10");
        p.Begin('UI  ', H("CONTROL SB ON UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 48.0f, 36.0f, 0.0f };
        a.dim[0] = 544; a.dim[1] = 408;
        p.Begin('UI  ', H("XBOX_SAFE_AREA UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 130.0f, 385.0f, 99.0f };
        a.seeThru = 0.5f;
        a.seeThruSpeed = 1.0f;
        a.dim[0] = 380; a.dim[1] = 60;
        a.textureID = H("textbox_alpha2");
        p.Begin('UI  ', H("MNU4 NPCTALK UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 80.0f, 375.0f, 99.0f };
        a.seeThru = 0.5f;
        a.seeThruSpeed = 1.0f;
        a.dim[0] = 480; a.dim[1] = 80;
        a.textureID = H("textbox_alpha2");
        p.Begin('UI  ', H("MNU4 MESSAGEBOX UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 120.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI BOSS 01"), a);
        p.Link(eEventPadPressRight, eEventUIFocusOff_Unselect, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventPadPressRight, eEventUIFocusOn_Select, H("TASK GLOW UI BOSS 02"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 01"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 170.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI BOSS 02"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI BOSS 02"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 02"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 02"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 220.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI BOSS 03"), a);
        p.Link(eEventPadPressLeft, eEventUIFocusOff_Unselect, H("TASK GLOW UI BOSS 03"));
        p.Link(eEventPadPressLeft, eEventUIFocusOn_Select, H("TASK GLOW UI BOSS 02"));
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 03"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 03"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 120.0f, 180.0f, 2.0f };
        a.dim[0] = 70; a.dim[1] = 70;
        a.textureID = H("ui_bubble_png");
        p.Begin('UI  ', H("TASK GLOW UI SMALLBOSS 01"), a);
        p.Link(eEventUISelect, eEventUIFocusOn, H("PAUSE TASK UIF 01"));
        p.Link(eEventUIUnselect, eEventUIFocusOff, H("PAUSE TASK UIF 01"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 130.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 01"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 180.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 02"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 230.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 03"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 04"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 05"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 06"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 07"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 190.0f, 1.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x387B19E4;
        p.Begin('UI  ', H("TASK GOLDEN UI 08"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 130.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 01"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 180.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 02"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 230.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 03"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 280.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 04"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 330.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 05"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 380.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 06"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 430.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 07"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 480.0f, 190.0f, 3.0f };
        a.scale = xVec3{ 1.1f, 1.1f, 0.2f };
        a.modelInfoID = 0x99841860;
        p.Begin('UI  ', H("TASK UI 08"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 430.0f, 180.0f, 0.0f };
        a.dim[0] = 128; a.dim[1] = 128;
        p.Begin('UI  ', H("MNU4 THUMBICON"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 85.0f, 5.0f, 90.0f };
        a.scale = xVec3{ 1.3f, 1.31f, 0.1f };
        a.modelInfoID = H("ui_3dicon_bamboo_01");
        a.dim[0] = 480; a.dim[1] = 480;
        p.Begin('UI  ', H("BLUE ALPHA 2 BAMBOO UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ -33.0f, -205.0f, 90.0f };
        a.scale = xVec3{ 1.26f, 1.33f, 0.1f };
        a.modelInfoID = H("ui_3dicon_bamboo_02");
        a.dim[0] = 480; a.dim[1] = 480;
        p.Begin('UI  ', H("BLUE ALPHA 3 BAMBOO UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 84.0f, 5.0f, 90.0f };
        a.scale = xVec3{ 1.3f, 1.31f, 0.1f };
        a.modelInfoID = H("ui_3dicon_bamboo_01");
        a.dim[0] = 480; a.dim[1] = 480;
        p.Begin('UI  ', H("BLUE ALPHA 1 BAMBOO UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 225.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.2f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM OFF SMALL UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 523.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.5f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM ON UI0"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 523.0f, 198.0f, 3.0f };
        a.scale = xVec3{ 1.2f, 0.9f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 70; a.dim[1] = 70;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("KABLAM ON SMALL UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x1D;
        a.surfaceID = H("MNU4 CAUSTICS SURFACE");
        a.pos = xVec3{ 220.0f, 140.0f, 0.0f };
        a.scale = xVec3{ 3.4f, 2.6f, 0.0f };
        a.modelInfoID = H("ui_3dicon_caustics");
        a.dim[0] = 200; a.dim[1] = 200;
        p.Begin('UI  ', H("AAA MNU4 CAUSTICS SURFACE UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 190.0f, 160.0f, 0.0f };
        a.scale = xVec3{ -1.0f, 0.38f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 260; a.dim[1] = 100;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("PAUSE GAME PAUSED KABLAM UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.ang = xVec3{ 3.1415927f, 0.0f, 0.0f };
        a.pos = xVec3{ 275.0f, 350.0f, 3.0f };
        a.scale = xVec3{ 1.0f, 1.0f, 0.1f };
        a.modelInfoID = H("ui_3dicon_savegame");
        a.animListID = H("SAVING GAME ANIM LIST");
        a.dim[0] = 90; a.dim[1] = 90;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("SAVING GAME ICON UI"), a);
        p.Link(eEventVisible, eEventVisible, H("MNU4 AUTO SAVE"));
        p.Link(eEventInvisible, eEventInvisible, H("MNU4 AUTO SAVE"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 135.0f, 108.0f, 2.0f };
        a.scale = xVec3{ 1.0f, 0.29f, 0.1f };
        a.modelInfoID = H("ui_3dicon_kablam");
        a.animListID = H("KABLAM ANIM LIST");
        a.dim[0] = 360; a.dim[1] = 200;
        a.uva[0] = 1.0f; a.uva[1] = 0.0f;
        a.uvb[0] = 0.0f; a.uvb[1] = 0.0f;
        a.uvc[0] = 0.0f; a.uvc[1] = 1.0f;
        a.uvd[0] = 1.0f; a.uvd[1] = 1.0f;
        p.Begin('UI  ', H("TAXI CONFIRM KABLAM UI"), a);
        p.Link(eEventVisible, eEventInvisible, H("GAME PAUSED GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 290.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 14"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 300.0f, 1.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_small");
        p.Begin('UI  ', H("LEVEL OFF UI 15"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 290.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 14"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 14"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 14"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 14"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 13"));
        p.Link(eEventPadPressDown, eEventUIFocusOff_Unselect, H("LEVEL ON UI 14"));
        p.Link(eEventPadPressDown, eEventUIFocusOn_Select, H("LEVEL ON UI 15"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF14"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF14"));
        p.Link(eEventPadPressUp, eEventInvisible, H("TASK SPATULA ALL GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("TASK GLOW UI GROUP"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("TASK GLOW UI BOSS 01"));
        p.Link(eEventPadPressUp, eEventVisible, H("TASK SPATULA 3 GROUP"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.pos = xVec3{ 70.0f, 300.0f, 0.0f };
        a.dim[0] = 30; a.dim[1] = 30;
        a.textureID = H("ui_bubble_big");
        p.Begin('UI  ', H("LEVEL ON UI 15"), a);
        p.Link(eEventUISelect, eEventVisible, H("LEVEL ON UI 15"));
        p.Link(eEventUIUnselect, eEventInvisible, H("LEVEL ON UI 15"));
        p.Link(eEventPadPressUp, eEventUIFocusOff_Unselect, H("LEVEL ON UI 15"));
        p.Link(eEventPadPressUp, eEventUIFocusOn_Select, H("LEVEL ON UI 14"));
        p.Link(eEventUISelect, eEventVisible, H("PAUSE LEVEL UIF15"));
        p.Link(eEventUIUnselect, eEventInvisible, H("PAUSE LEVEL UIF15"));
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 120.0f, 290.0f, 0.2f };
        a.scale = xVec3{ 1.0f, 1.0f, 0.1f };
        a.modelInfoID = 0xAB037E3D;
        p.Begin('UI  ', H("UI_LEVEL_PATSOCK"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 65.0f, 85.0f, 0.0f };
        a.seeThru = 0.5f;
        a.seeThruSpeed = 1.0f;
        a.dim[0] = 510; a.dim[1] = 60;
        a.textureID = H("textbox_alpha2");
        p.Begin('UI  ', H("MNU4 AUTOSAVE UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 200.0f, 225.0f, 0.0f };
        a.seeThru = 0.5f;
        a.seeThruSpeed = 1.0f;
        a.dim[0] = 250; a.dim[1] = 60;
        a.textureID = H("textbox_alpha2");
        p.Begin('UI  ', H("MNU4 SAVE COMPLETED UI"), a);
        p.End();
    }

    {
        zUIAsset a = kUIDefaults;
        a.baseFlags = 0x5;
        a.moreFlags = 0;
        a.pos = xVec3{ 40.0f, 50.0f, 0.0f };
        a.seeThru = 0.5f;
        a.seeThruSpeed = 1.0f;
        a.dim[0] = 550; a.dim[1] = 240;
        a.textureID = H("textbox_alpha2");
        p.Begin('UI  ', H("MNU4 AUTO SAVE FAILED UI"), a);
        p.Link(eEventVisible, eEventRun, H("AUTO_SAVE_FAILED_TIMER"));
        p.End();
    }
}
