// Generated by tools/menugen/menugen.py from the Xbox mnu4.HIP, then kept by
// hand. This file is the source of MNU4's HUD widgets, text boxes and talk
// boxes now; edit it directly. See src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static ztextbox::asset_type TextBoxDefaultsInit()
{
    ztextbox::asset_type a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("game_object:text_box");
    a.version = 1;
    a.text = H("INTENTIONALLY BLANK TXT");
    a.bounds.x = 0.1f;
    a.bounds.y = 0.85f;
    a.bounds.w = 0.8f;
    a.bounds.h = 0.1f;
    a.size.width = 0.042f;
    a.size.height = 0.069f;
    a.color.r = 255;
    a.color.g = 230;
    a.color.a = 255;
    a.xjustify = ztextbox::asset_type::XJ_CENTER;
    a.expand = (decltype(a.expand))100;
    a.backdrop.type = 100;
    a.backdrop.color.r = 255;
    a.backdrop.color.g = 255;
    a.backdrop.color.b = 255;
    a.backdrop.color.a = 255;
    return a;
}

static const ztextbox::asset_type kTextBoxDefaults = TextBoxDefaultsInit();

static xhud::font_meter_asset HudFontMeterDefaultsInit()
{
    xhud::font_meter_asset a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("hud:meter:font");
    a.version = 3;
    a.loc = xVec3{ 0.71f, 0.1f, 0.0f };
    a.size = xVec3{ 0.05f, 0.07f, 0.0f };
    a.max_value = -1.0f;
    a.increment_time = 0.1f;
    a.decrement_time = 0.1f;
    a.sound.increment = H("mnu4_Pop_in");
    a.sound.decrement = H("mnu4_Pop_in");
    a.font.id = 0x00000003;
    a.font.w = 0.125f;
    a.font.h = 0.125f;
    a.font.drop_x = 0.01f;
    a.font.drop_y = 0.01f;
    a.font.c.r = 255;
    a.font.c.g = 230;
    a.font.c.a = 255;
    a.font.drop_c.g = 70;
    a.font.drop_c.b = 85;
    a.font.drop_c.a = 200;
    return a;
}

static const xhud::font_meter_asset kHudFontMeterDefaults = HudFontMeterDefaultsInit();

static xhud::unit_meter_asset HudUnitMeterDefaultsInit()
{
    xhud::unit_meter_asset a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("hud:meter:unit");
    a.version = 3;
    a.loc = xVec3{ 0.09f, 0.14f, 0.04f };
    a.size = xVec3{ 0.07f, 0.07f, 0.0f };
    a.start_value = 3.0f;
    a.max_value = 5.0f;
    a.increment_time = 0.5f;
    a.sound.start_increment = 0xDF72D7B9;
    a.model[0].id = 0xD36E17AA;
    a.model[0].size = xVec3{ 1.0f, 1.0f, 0.0f };
    a.model[1].id = 0xA59A686D;
    a.model[1].size = xVec3{ 1.0f, 1.0f, 0.0f };
    a.offset = xVec3{ 0.055f, 0.0f, 0.0001f };
    a.fill_forward = 1;
    return a;
}

static const xhud::unit_meter_asset kHudUnitMeterDefaults = HudUnitMeterDefaultsInit();

static xhud::model_asset HudModelDefaultsInit()
{
    xhud::model_asset a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("hud:model");
    a.version = 1;
    a.loc = xVec3{ 0.08f, 0.83f, 0.003f };
    a.size = xVec3{ 0.09f, 0.09f, 0.0f };
    a.model = 0xAB037E3D;
    return a;
}

static const xhud::model_asset kHudModelDefaults = HudModelDefaultsInit();

static xhud::text_asset HudTextDefaultsInit()
{
    xhud::text_asset a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("hud:text");
    a.version = 1;
    a.loc = xVec3{ 0.1f, 0.85f, 0.0f };
    a.size = xVec3{ 0.8f, 0.1f, 0.0f };
    a.text_box = H("TEXTBOX_COMBOBOX");
    a.text = H("INTENTIONALLY BLANK TXT");
    return a;
}

static const xhud::text_asset kHudTextDefaults = HudTextDefaultsInit();

void MNU4_BuildDyna(iAssetPkg& p)
{
    {
        ztextbox::asset_type a = kTextBoxDefaults;
        p.Begin('DYNA', H("TEXTBOX_COMBOBOX"), a);
        p.End();
    }

    {
        xhud::font_meter_asset a = kHudFontMeterDefaults;
        a.increment_time = 0.025f;
        a.decrement_time = 0.01f;
        a.sound.start_increment = H("shiny_object_triangle3_soft");
        a.sound.increment = H("shiny_object_triangle3_soft");
        a.sound.start_decrement = H("shiny_object_triangle3_soft");
        a.sound.decrement = H("shiny_object_triangle3_soft");
        p.Begin('DYNA', H("HUD_INT_METER_SHINY"), a);
        p.End();
    }

    {
        xhud::font_meter_asset a = kHudFontMeterDefaults;
        a.loc = xVec3{ 0.51f, 0.1f, 0.0f };
        a.sound.increment = 0;
        a.sound.decrement = 0;
        p.Begin('DYNA', H("HUD_INT_METER_SPATULA"), a);
        p.End();
    }

    {
        xhud::font_meter_asset a = kHudFontMeterDefaults;
        a.loc = xVec3{ 0.18f, 0.793f, 0.0f };
        a.counter_mode = 1;
        p.Begin('DYNA', H("HUD_INT_METER_SPECIAL"), a);
        p.End();
    }

    {
        xhud::font_meter_asset a = kHudFontMeterDefaults;
        a.loc = xVec3{ 0.83f, 0.793f, 0.0f };
        a.font.justify = 1;
        p.Begin('DYNA', H("HUD_INT_METER_PATSSOCK"), a);
        p.End();
    }

    {
        xhud::unit_meter_asset a = kHudUnitMeterDefaults;
        p.Begin('DYNA', H("HUD_UNIT_METER_HEALTH"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.loc = xVec3{ 0.63f, 0.125f, 0.001f };
        a.size = xVec3{ 0.06f, 0.06f, 0.0f };
        a.model = 0x254749B1;
        p.Begin('DYNA', H("HUD_MODEL_SHINY"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.loc = xVec3{ 0.44f, 0.115f, 0.002f };
        a.size = xVec3{ 0.07f, 0.07f, 0.0f };
        a.model = 0x387B19E4;
        p.Begin('DYNA', H("HUD_MODEL_SPATULA"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = H("ui_3dicon_question");
        p.Begin('DYNA', H("HUD_MODEL_SPECIAL"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.loc = xVec3{ 0.73f, 0.815f, 0.003f };
        p.Begin('DYNA', H("HUD_MODEL_PATSSOCK"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.size = xVec3{ 0.1f, 0.1f, 0.0f };
        a.model = 0xFFE5F710;
        p.Begin('DYNA', H("HUD_MODEL_JF_ANTITODE"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0x5EE98261;
        p.Begin('DYNA', H("HUD_MODEL_BB_STEERINGWHEEL"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0xA439E716;
        p.Begin('DYNA', H("HUD_MODEL_GL_BALLOON"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0x1D9BFE7D;
        p.Begin('DYNA', H("HUD_MODEL_RB_ARTPIECES"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0xD5DC44C4;
        p.Begin('DYNA', H("HUD_MODEL_BC_SECURITYBUTTONS"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0x715D2168;
        p.Begin('DYNA', H("HUD_MODEL_KF_LIGHTCRYSTALS"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.model = 0x717EEE0B;
        p.Begin('DYNA', H("HUD_MODEL_GY_CANNONS"), a);
        p.End();
    }

    {
        xhud::model_asset a = kHudModelDefaults;
        a.loc = xVec3{ 0.2f, 0.61f, 0.003f };
        a.size = xVec3{ 0.06f, 0.06f, 0.0f };
        p.Begin('DYNA', H("HUD_MODEL_PATSSOCK PER LEVEL"), a);
        p.End();
    }

    {
        xhud::text_asset a = kHudTextDefaults;
        p.Begin('DYNA', H("HUD_TEXT_COMBOMESSAGE"), a);
        p.End();
    }
}
