// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's UI widgets now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static zUIAsset UIDefaultsInit()
{
    zUIAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeUI;
    a.baseFlags = 0x1D;
    a.moreFlags = 0x2;
    a.pos = xVec3{ 0.0f, 0.0f, 91.0f };
    a.scale = xVec3{ 1.0f, 1.0f, 1.0f };
    a.redMult = 1.0f;
    a.greenMult = 1.0f;
    a.blueMult = 1.0f;
    a.seeThru = 1.0f;
    a.seeThruSpeed = 255.0f;
    a.uiFlags = 0x34;
    a.dim[0] = 640; a.dim[1] = 480;
    a.uvb[0] = 1.0f; a.uvb[1] = 0.0f;
    a.uvc[0] = 1.0f; a.uvc[1] = 1.0f;
    a.uvd[0] = 0.0f; a.uvd[1] = 1.0f;
    return a;
}

static const zUIAsset kUIDefaults = UIDefaultsInit();

void MNU5_BuildUI(iAssetPkg& p)
{
    {
        zUIAsset a = kUIDefaults;
        p.Begin('UI  ', H("FLYTHRU_UI"), a);
        p.End();
    }
}
