// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's asset list now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

// The types this package builds. The HIP's own assets of these types are
// never seen; everything else in it is used as shipped.
extern const U32 kMNU5OwnedTypes[] = { 'TEXT', 'UI  ', 'UIFT', 'DYNA', 'CNTR', 0 };

void MNU5_BuildText(iAssetPkg& p);
void MNU5_BuildUI(iAssetPkg& p);
void MNU5_BuildUIFont(iAssetPkg& p);
void MNU5_BuildDyna(iAssetPkg& p);
void MNU5_BuildCounter(iAssetPkg& p);

void MNU5_Build(iAssetPkg& p)
{
    MNU5_BuildText(p);
    MNU5_BuildUI(p);
    MNU5_BuildUIFont(p);
    MNU5_BuildDyna(p);
    MNU5_BuildCounter(p);
}
