// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's HUD widgets, text boxes and talk
// boxes now; edit it directly. See src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static ztalkbox::asset_type TalkBoxDefaultsInit()
{
    ztalkbox::asset_type a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("game_object:talk_box");
    a.version = 11;
    a.dialog_box = H("DIALOG_TEXTBOX");
    a.prompt_box = H("PROMPT_TEXTBOX");
    a.quit_box = H("QUIT_TEXTBOX");
    a.allow_quit = 1;
    a.auto_wait.type.prompt = 1;
    a.prompt.skip = H("text_menu_continue");
    a.prompt.quit = H("text_menu_quit");
    return a;
}

static const ztalkbox::asset_type kTalkBoxDefaults = TalkBoxDefaultsInit();

static ztextbox::asset_type TextBoxDefaultsInit()
{
    ztextbox::asset_type a;
    memset(&a, 0, sizeof(a));
    a.baseFlags = 0x1D;
    a.type = H("game_object:text_box");
    a.version = 1;
    a.bounds.x = 0.1f;
    a.bounds.y = 0.84f;
    a.bounds.w = 0.8f;
    a.bounds.h = 0.01f;
    a.size.width = 0.035f;
    a.size.height = 0.057f;
    a.color.r = 4;
    a.color.g = 57;
    a.color.b = 95;
    a.color.a = 255;
    a.inset.left = 0.05f;
    a.inset.top = 0.01f;
    a.inset.right = 0.01f;
    a.xjustify = ztextbox::asset_type::XJ_CENTER;
    a.expand = (decltype(a.expand))100;
    a.backdrop.type = 1;
    a.backdrop.color.r = 255;
    a.backdrop.color.g = 255;
    a.backdrop.color.b = 255;
    a.backdrop.color.a = 255;
    a.backdrop.texture = H("textbox_alpha2");
    return a;
}

static const ztextbox::asset_type kTextBoxDefaults = TextBoxDefaultsInit();

void MNU5_BuildDyna(iAssetPkg& p)
{
    {
        ztalkbox::asset_type a = kTalkBoxDefaults;
        p.Begin('DYNA', H("OUT_OF_BOUNDS_TLKBX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.text = H("exit_hub_text");
        a.bounds.y = 0.76f;
        a.bounds.h = 0.16f;
        a.inset.top = 0.02f;
        a.inset.right = 0.05f;
        a.expand = ztextbox::asset_type::EX_DOWN;
        a.max_height = 0.138f;
        p.Begin('DYNA', H("MESSAGE_02_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.y = 0.61f;
        a.bounds.h = 0.22f;
        a.size.height = 0.055f;
        a.inset.left = 0.03f;
        a.inset.top = 0.02f;
        a.inset.right = 0.03f;
        p.Begin('DYNA', H("DIALOG_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.x = 0.6f;
        a.bounds.w = 0.3f;
        a.inset.left = 0.01f;
        a.inset.bottom = 0.01f;
        a.expand = ztextbox::asset_type::EX_DOWN;
        a.max_height = 0.15f;
        p.Begin('DYNA', H("PROMPT_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.w = 0.3f;
        a.inset.left = 0.01f;
        a.inset.bottom = 0.01f;
        a.expand = ztextbox::asset_type::EX_DOWN;
        a.max_height = 0.15f;
        p.Begin('DYNA', H("QUIT_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.y = 0.4f;
        a.bounds.h = 0.4f;
        a.size.width = 0.06f;
        a.size.height = 0.09f;
        a.color.r = 255;
        a.color.g = 230;
        a.color.b = 70;
        a.inset.right = 0.05f;
        a.inset.bottom = 0.01f;
        a.backdrop.type = 100;
        a.backdrop.texture = 0;
        p.Begin('DYNA', H("MESSAGE_01_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.x = 0.725f;
        a.bounds.y = 0.2f;
        a.bounds.w = 0.175f;
        a.bounds.h = 0.125f;
        a.size.width = 0.07f;
        a.size.height = 0.114f;
        a.color.r = 0;
        a.color.g = 0;
        a.color.b = 192;
        a.inset.left = 0.0f;
        a.inset.top = 0.0f;
        a.backdrop.color.r = 226;
        a.backdrop.color.b = 235;
        p.Begin('DYNA', H("TIMER_TEXTBOX"), a);
        p.End();
    }

    {
        ztextbox::asset_type a = kTextBoxDefaults;
        a.bounds.x = 0.725f;
        a.bounds.y = 0.35f;
        a.bounds.w = 0.175f;
        a.bounds.h = 0.125f;
        a.size.width = 0.07f;
        a.size.height = 0.114f;
        a.color.r = 0;
        a.color.g = 0;
        a.color.b = 192;
        a.inset.left = 0.0f;
        a.inset.top = 0.0f;
        a.backdrop.color.r = 226;
        a.backdrop.color.b = 235;
        a.backdrop.texture = H("textbox_alpha_froz");
        p.Begin('DYNA', H("FREEZY_TIMER_TEXTBOX"), a);
        p.End();
    }
}
