// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's text widgets now; edit it directly.
// See src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static zUIFontAsset UIFontDefaultsInit()
{
    zUIFontAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeUIFont;
    a.baseFlags = 0x1D;
    a.moreFlags = 0x2;
    a.pos = xVec3{ 170.0f, 390.0f, 1.0f };
    a.scale = xVec3{ 1.0f, 1.0f, 1.0f };
    a.redMult = 1.0f;
    a.greenMult = 1.0f;
    a.blueMult = 1.0f;
    a.seeThru = 1.0f;
    a.seeThruSpeed = 255.0f;
    a.uiFlags = 0x34;
    a.dim[0] = 300; a.dim[1] = 60;
    a.uvb[0] = 1.0f; a.uvb[1] = 0.0f;
    a.uvc[0] = 1.0f; a.uvc[1] = 1.0f;
    a.uvd[0] = 0.0f; a.uvd[1] = 1.0f;
    a.uiFontFlags = 0x164;
    a.textAssetID = H("flythrough_jf01_txt");
    a.bcolor[0] = 128; a.bcolor[1] = 128; a.bcolor[2] = 128; a.bcolor[3] = 128;
    a.color[0] = 255; a.color[1] = 230; a.color[2] = 0; a.color[3] = 255;
    a.inset[0] = 2; a.inset[1] = 2; a.inset[2] = 2; a.inset[3] = 2;
    a.space[0] = 24; a.space[1] = 28;
    a.cdim[0] = 24; a.cdim[1] = 28;
    return a;
}

static const zUIFontAsset kUIFontDefaults = UIFontDefaultsInit();

void MNU5_BuildUIFont(iAssetPkg& p)
{
    {
        zUIFontAsset a = kUIFontDefaults;
        p.Begin('UIFT', H("JF01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_jf02_txt");
        p.Begin('UIFT', H("JF02_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_jf04_txt");
        p.Begin('UIFT', H("JF04_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_bb01_txt");
        p.Begin('UIFT', H("BB01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_bb04_txt");
        p.Begin('UIFT', H("BB04_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_sm02_txt");
        p.Begin('UIFT', H("SM02_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_hb01_txt");
        p.Begin('UIFT', H("HB01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_pg12_txt");
        p.Begin('UIFT', H("PG12_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_gl01_txt");
        p.Begin('UIFT', H("GL01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_gl02_txt");
        p.Begin('UIFT', H("GL02_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_bc02_txt");
        p.Begin('UIFT', H("BC02_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_db01_txt");
        p.Begin('UIFT', H("DB01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_gy01_txt");
        p.Begin('UIFT', H("GY01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_kf01_txt");
        p.Begin('UIFT', H("KF01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_sm01_txt");
        p.Begin('UIFT', H("SM01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_rb01_txt");
        p.Begin('UIFT', H("RB01_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_b101_txt");
        p.Begin('UIFT', H("B101_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_sm03_txt");
        p.Begin('UIFT', H("SM03_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_sm04_txt");
        p.Begin('UIFT', H("SM04_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_kf05_txt");
        p.Begin('UIFT', H("KF05_FLYTHRU_UIF"), a);
        p.End();
    }

    {
        zUIFontAsset a = kUIFontDefaults;
        a.textAssetID = H("flythrough_db02_txt");
        p.Begin('UIFT', H("DB02_FLYTHRU_UIF"), a);
        p.End();
    }
}
