// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's counters now; edit it directly. See
// src/SB/Core/pc/menu/README.md.
#include "iAssetBuild.h"

static xCounterAsset CounterDefaultsInit()
{
    xCounterAsset a;
    memset(&a, 0, sizeof(a));
    a.baseType = eBaseTypeCounter;
    a.baseFlags = 0x1D;
    return a;
}

static const xCounterAsset kCounterDefaults = CounterDefaultsInit();

void MNU5_BuildCounter(iAssetPkg& p)
{
    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("JF_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BB_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GL_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("B1_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("RB_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("BC_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("SM_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("B2_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KF_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("GY_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("DB_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("B3_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("B3_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("B3_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PG_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 09"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 10"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 11"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 12"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("KS_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_01"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_02"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_03"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_04"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_05"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_06"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_07"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("PS_TASK_COUNTER_08"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        a.baseFlags = 0x1F;
        p.Begin('CNTR', H("HB01_FREE_MOVIE_PASS"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 13"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 14"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("HB09 ROBOT COUNTER 15"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        p.Begin('CNTR', H("REMINDER_SOCK_CNTR"), a);
        p.End();
    }

    {
        xCounterAsset a = kCounterDefaults;
        a.baseFlags = 0x1F;
        p.Begin('CNTR', H("RETURN TO PG12 COUNTER"), a);
        p.End();
    }
}
