// Generated by tools/menugen/menugen.py from the Xbox mnu5.HIP, then kept by
// hand. This file is the source of MNU5's text now; edit it directly. See
// src/SB/Core/pc/menu/README.md.

#include "iAssetBuild.h"

void MNU5_BuildText(iAssetPkg& p)
{
    p.Text(H("flythrough_b101_txt"), "Sandy Robot Battle");
    p.Text(H("flythrough_bb01_txt"), "Downtown Bikini Bottom");
    p.Text(H("flythrough_bb04_txt"), "The Sea Needle");
    p.Text(H("flythrough_bc02_txt"), "The Mermalair");
    p.Text(H("flythrough_db01_txt"), "SpongeBob's Dream");
    p.Text(H("flythrough_db02_txt"), "Sandy's Dream");
    p.Text(H("flythrough_gl01_txt"), "Goo Lagoon");
    p.Text(H("flythrough_gl02_txt"), "The Sea Caves");
    p.Text(H("flythrough_gy01_txt"), "Graveyard Lake");
    p.Text(H("flythrough_hb01_txt"), "Bikini Bottom");
    p.Text(H("flythrough_jf01_txt"), "Jellyfish Fields");
    p.Text(H("flythrough_jf02_txt"), "Jellyfish Caves");
    p.Text(H("flythrough_jf04_txt"), "King Jellyfish Battle");
    p.Text(H("flythrough_kf01_txt"), "The Kelp Forest");
    p.Text(H("flythrough_kf05_txt"), "Kelp Vines");
    p.Text(H("flythrough_pg12_txt"), "SpongeBall Skate Park");
    p.Text(H("flythrough_rb01_txt"), "Rock Bottom");
    p.Text(H("flythrough_sm01_txt"), "Ski Lodge");
    p.Text(H("flythrough_sm02_txt"), "Guppy Mound");
    p.Text(H("flythrough_sm03_txt"), "Flounder Hill");
    p.Text(H("flythrough_sm04_txt"), "Sand Mountain");
    p.Text(H("mnu5 taxi warning txt"), "Only SpongeBob can take the taxi.");
    p.Text(H("out_of_bounds_txt"), "If {r=0}{g=0.2}{b=0}{var:PlayerName}{~:c} walks too far out of the gameplay area, {var:PlayerHeShe} will be placed back at the last checkpoint.");
}
