#ifndef IASSETOVERRIDE_H
#define IASSETOVERRIDE_H

#include <types.h>

// PC-only: packages whose logic assets come from code instead of the HIP.
//
// A package listed in iAssetOverride.cpp names the asset types it owns and a
// function that builds them (src/SB/Core/pc/menu). When the game opens that
// HIP, the function runs, and from then on every lookup of an owned type in
// that package -- by ID, by type and index, by count -- answers from the
// built assets. The HIP's own assets of those types are still read but never
// seen. Every other type, and every other package, is untouched.
//
// **Where it hooks in.** xstransvc.cpp reaches packages only through the
// packer's function table, so this wraps the table rather than touching the
// packer or any caller. The wrapper is iFilePackageReadFuncs, declared in
// iFile.h and defined in iAssetOverride.cpp.
//
// **Checking a copy against the HIP.** With BFBB_ASSET_VERIFY=1 in the
// environment, the first lookup after the HIP finishes loading compares every
// built asset with the HIP asset of the same ID and prints each difference.
// A package generated by tools/menugen and not yet edited reports none.

// Off leaves every package exactly as the disc shipped it. Pushed from
// iSystem.cpp's ApplyConfig. Read when a package opens.
void iAssetOverrideSetEnabled(S32 on);

// Whether the PC menus are on ([assets] code_menu). The PC save screen and the
// save folders it reaches follow this too, so off is retail throughout.
S32 iAssetOverrideEnabled();

// Rewrite a code-built TEXT asset's string, cut to the room it was built with
// (iAssetPkg::TextSpace). FALSE when no open package built one by that ID.
S32 iAssetTextSet(U32 id, const char* text);

#endif
